### ISSUE TITLE
DW1830 third connector

### ISSUE THREAD

**Issue by ghost** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#10]
Hi, posting here as well although I did post here:

https://www.tonymacx86.com/threads/macos-10-14-0-thinkpad-x1-extreme-hackintosh.263916/page-6

I bought the DW1830 and the X1E. Both should be here within the next few days. The DW1830 has three connectors (3x3) I believe, but I think the one that comes with X1E is a (2x2). Did you install a third antenna or just leave it unplugged? If so, what connectors are you using. I've read of people leaving it unplugged, but then some say not to do that, some others link to antennas which are not NGFF/M.2 according to the listing. I believe this laptop takes NGFF/M.2 cards.

Or should I just get a DW1560 to make things somewhat easier?

**Comment by wu-hongjun** [comment]
Yes. I installed a 3rd antenna. See the bluetooth issue and I believe we have some good pictures posted. https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/3#issuecomment-447688126

**Comment by ghost** [comment]
Awesome thanks! Did you run it through the hinges and display, or leave it in the chassis?

**Comment by wu-hongjun** [comment]
I just left it in the chassis. If you look into it, it’s actually a pretty good place for the antenna.
