### ISSUE TITLE
Does USB Work? / 请问usb接口可以正常使用吗

### ISSUE THREAD

**Issue by summerfish** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#12]
想问下大神您的usb接口可以正常使用吗，我的机器x1e, 加了一块512g的三星970 pro专门用来安装黑苹果，目前是10.14.3的系统，其他基本都正常，但是右侧的两个usb接口好像无法驱动，接上任何usb设备都没反应，左侧的雷电3接口，使用雷电3转usb的转接器，貌似只能识别出来U盘和移动硬盘，其他的USB外设比如键盘和鼠标，连接上去都没反应，无法识别。

**Comment by darkal** [comment]
可以左右侧USB都可以正常使用

**Comment by wu-hongjun** [comment]
可以
