### ISSUE TITLE
dw1830 wifi adapter have two different module?

### ISSUE THREAD

**Issue by wdde** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#14]
General edition doesn't compat with lenovo, is it right? I can't find the lenovo compatible version in the taobao.com，please help to confirm where is the correct dw1830 should I look for. Thanks

**Comment by wdde** [comment]
I am also trying to find other alternatives, dw1560 looks longer than dw1830, I can't confirm whether it can install it properly. bcm94360cs This is Apple's original wifi, it seems to need a converter to fix, where is the converter shopping links?

**Comment by wu-hongjun** [comment]
General DW1830 works. I have both BCM943602BAED(DW1830) and BCM943602CS(Apple Card) and both can be recognized in macOS. Keep in mind that for the apple wireless card you need an adapter.

**Comment by wdde** [comment]
I am making a decision to choose ine between dw1830 and 1520a, 1830 is much expensive, is it worth?

**Comment by wu-hongjun** [comment]
I don't know since I don't have a 1520A, but theoretically, it should work fine since all that you do is connect to wifi. Shouldn't make that big of a difference, but I do recommend you go do some more research regarding this issue. Hope it helps.

**Comment by wdde** [comment]
Thanks.
