### ISSUE TITLE
No luck, bcm943602cs cause my x1e hang

### ISSUE THREAD

**Issue by wdde** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#15]
运气好差啊，我昨晚以为全搞定了。今天发现，在windows10下，无线网只要连接到wifi，几分钟就会死机，而且是一动不动的完全死掉，在macos下，连接wifi几分钟后就会直接重启。

Luck is so bad, I thought I was all done last night. Today I found that in windows 10, as long as the wireless network is connected to wifi, the windows 10 will hang in a few minutes, and it is completely dead, mouse pointer,keyboard give no reflection. In macos, after connecting to wifi for a few minutes, it will reset directly.

**Comment by wu-hongjun** [comment]
Wait wtf is this I have no problem with my BCM94360CS2. Double check that the adapter card is plugged in fully and also make sure you use a piece of electrical tape to insulate the card from the motherboard to prevent any shorting that will eventually destroy your laptop.

我咋没这问题啊？？？你看看你转接卡卡有没有完全插进去？以及记得用电工胶布绝缘BCM943602CS的背面防止短路或者磕到PCH。你这个是真的 运气差……

**Comment by wdde** [comment]
我真是愚蠢，我买的时候看错了，把94360cs2当成943902cs买到手，结果就是死机，最近几天换成943602cs，什么问题都没有了，昨天下单买了dw1830,希望运气能好点，我还是觉得943602太长太厚了，

I am too stupid. I bought it wrong. I bought the 94460cs2 as 943602cs. The result is a crash. In recent days, I changed to 943602cs. I have no problem. Ordered a dw1830 yesterday, hope good luck, the 02cs still too long and too thick.

**Comment by wu-hongjun** [comment]
好问题，我会收录进Readme.MD，谢谢分享。

Good issue. I will index it in the readme.MD to warn other humans about this issue, thanks for sharing!

**Comment by wu-hongjun** [comment]
我买了一个CS2 没问题啊？好的一批……

I got a BCM94360CS2 and it works fine...for me...

![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)

**Comment by darkal** [comment]
> 我买了一个CS2 没问题啊？好的一批……
> 
> I got a BCM94360CS2 and it works fine...for me...
> 
> ![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)

BCM94360CS2 信号更好吗？

**Comment by wu-hongjun** [comment]
两根天线无需机内加装信号好的一批 蓝牙我戴着AirPods都惊了我走开五十米去上洗手间隔着一堵墙声音丝滑还以为连的是手机

**Comment by wu-hongjun** [comment]
> > 我买了一个CS2 没问题啊？好的一批……
> > I got a BCM94360CS2 and it works fine...for me...
> > ![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)
> 
> BCM94360CS2 信号更好吗？

我凉了 用了一个星期死机了 还把我Windows也搞死机了 佛了

**Comment by darkal** [comment]
> > > 我买了一个CS2 没问题啊？好的一批……
> > > I got a BCM94360CS2 and it works fine...for me...
> > > ![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)
> > 
> > 
> > BCM94360CS2 信号更好吗？
> 
> 我凉了 用了一个星期死机了 还把我Windows也搞死机了 佛了

...我买了BCM94360CS2，用了一个星期，感觉很稳定。。。

**Comment by wu-hongjun** [comment]
> > > > 我买了一个CS2 没问题啊？好的一批……
> > > > I got a BCM94360CS2 and it works fine...for me...
> > > > ![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)
> > > 
> > > 
> > > BCM94360CS2 信号更好吗？
> > 
> > 
> > 我凉了 用了一个星期死机了 还把我Windows也搞死机了 佛了
> 
> ...我买了BCM94360CS2，用了一个星期，感觉很稳定。。。

曾经的我

**Comment by darkal** [comment]
> > > > > 我买了一个CS2 没问题啊？好的一批……
> > > > > I got a BCM94360CS2 and it works fine...for me...
> > > > > ![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)
> > > > 
> > > > 
> > > > BCM94360CS2 信号更好吗？
> > > 
> > > 
> > > 我凉了 用了一个星期死机了 还把我Windows也搞死机了 佛了
> > 
> > 
> > ...我买了BCM94360CS2，用了一个星期，感觉很稳定。。。
> 
> 曾经的我

我之前用BCM943602CS，经常死机，后面换了转接板加cs2，世界就清静了。。

**Comment by wu-hongjun** [comment]
> > > > > > 我买了一个CS2 没问题啊？好的一批……
> > > > > > I got a BCM94360CS2 and it works fine...for me...
> > > > > > ![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)
> > > > > 
> > > > > 
> > > > > BCM94360CS2 信号更好吗？
> > > > 
> > > > 
> > > > 我凉了 用了一个星期死机了 还把我Windows也搞死机了 佛了
> > > 
> > > 
> > > ...我买了BCM94360CS2，用了一个星期，感觉很稳定。。。
> > 
> > 
> > 曾经的我
> 
> 我之前用BCM943602CS，经常死机，后面换了转接板加cs2，世界就清静了。。

我和你正好相反？？？ 我是那款两根天线的把我两个系统都搞爆了

**Comment by darkal** [comment]
> > > > > > > 我买了一个CS2 没问题啊？好的一批……
> > > > > > > I got a BCM94360CS2 and it works fine...for me...
> > > > > > > ![BCM94360CS2](https://user-images.githubusercontent.com/27667864/58378224-5eb67e80-7f45-11e9-9076-79606d492396.jpg)
> > > > > > 
> > > > > > 
> > > > > > BCM94360CS2 信号更好吗？
> > > > > 
> > > > > 
> > > > > 我凉了 用了一个星期死机了 还把我Windows也搞死机了 佛了
> > > > 
> > > > 
> > > > ...我买了BCM94360CS2，用了一个星期，感觉很稳定。。。
> > > 
> > > 
> > > 曾经的我
> > 
> > 
> > 我之前用BCM943602CS，经常死机，后面换了转接板加cs2，世界就清静了。。
> 
> 我和你正好相反？？？ 我是那款两根天线的把我两个系统都搞爆了

是的。。我怀疑是接触不良，因为我的老转接卡和CS2有点松，事后重启看日志都提示网卡驱动崩溃

**Comment by darkal** [comment]
使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好

BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.

**Comment by wu-hongjun** [comment]
> 使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好
> 
> BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.

那么叼 我的第二天就黑屏了...看脸的吗...？？？

**Comment by Calciferx** [comment]
> 使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好
> 
> BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.

请问能把你的驱动分享一下吗？

**Comment by Calciferx** [comment]
> > 使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好
> > BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.
> 
> 那么叼 我的第二天就黑屏了...看脸的吗...？？？

请问你是在用自己焊的转接板的时候出现的这种问题，还是在用淘宝定制的转接板时？

**Comment by wu-hongjun** [comment]
自己悍的 淘宝的没试过


Hongjun Jack Wu
Email: hongjun@cs.washington.edu<mailto:hongjun@cs.washington.edu>
Resume: hongjunwu.com<http://hongjunwu.com/>
University of Washington


On Feb 21, 2020, at 1:31 AM, Calciferx <notifications@github.com> wrote:

﻿

使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好
BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.

那么叼 我的第二天就黑屏了...看脸的吗...？？？

请问你是在用自己焊的转接板的时候出现的这种问题，还是在用淘宝定制的转接板时？

**Comment by darkal** [comment]
> > 使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好
> > BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.
> 
> 请问能把你的驱动分享一下吗？

电脑卖掉换Macbook Pro 16了。。。MAC系统下是完全免驱的呀，不需要驱动，win下我记得就是网上随意百度下的一个

**Comment by Calciferx** [comment]
> > > 使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好
> > > BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.
> > 
> > 
> > 请问能把你的驱动分享一下吗？
> 
> 电脑卖掉换Macbook Pro 16了。。。MAC系统下是完全免驱的呀，不需要驱动，win下我记得就是网上随意百度下的一个

应该是处理器和芯片组的问题，如果我所料不错的话。带有vPro标志的8850H的机器使用cs2就会有问题，某些批次的2cs会导致插电自动开机。

**Comment by freeyoung** [comment]
我的 x1c 6th 也出现了类似问题，黑苹果正常，但是 Windows 10 下面一连 WiFi 就死机。

I'm suffering from the same issue on my x1c 6th. It works fine in macOS but freezes Windows 10 whenever I connect to WiFi.

**Comment by Calciferx** [comment]
> 我的 x1c 6th 也出现了类似问题，黑苹果正常，但是 Windows 10 下面一连 WiFi 就死机。
> 
> I'm suffering from the same issue on my x1c 6th. It works fine in macOS but freezes Windows 10 whenever I connect to WiFi.

可以尝试小新13pro上使用cs2的方法，屏蔽转接卡第十一和第十二针脚

**Comment by Calciferx** [comment]
> > > > 使用了两个月之后，更新一下，我使用2天线的BCM94360CS2很稳定，两个多月以来没有一次死机和重启，WIFI和蓝牙信号都很好
> > > > BCM94360CS2 (2 antennas) is very stable. There has been no crash or reboot in more than two months. Both WIFI and Bluetooth signals are very good.
> > > 
> > > 
> > > 请问能把你的驱动分享一下吗？
> > 
> > 
> > 电脑卖掉换Macbook Pro 16了。。。MAC系统下是完全免驱的呀，不需要驱动，win下我记得就是网上随意百度下的一个
> 
> 应该是处理器和芯片组的问题，如果我所料不错的话。带有vPro标志的8850H的机器使用cs2就会有问题，某些批次的2cs会导致插电自动开机。

问题确定，和2cs批次并没有关系，vantage或者联想电脑管家里 “usb充电” 选择“从关机开始充电”则一切正常，选择 “关闭” 或者“从睡眠开始充电”都会导致 插电自动开机。手边没有cs2了，不知道cs2的冻屏是否和此选项有关，另外参考小新13pro的解决方案屏蔽转接卡第11和第12针脚或许可以解决此问题

**Comment by freeyoung** [comment]
> > 我的 x1c 6th 也出现了类似问题，黑苹果正常，但是 Windows 10 下面一连 WiFi 就死机。
> > I'm suffering from the same issue on my x1c 6th. It works fine in macOS but freezes Windows 10 whenever I connect to WiFi.
> 
> 可以尝试小新13pro上使用cs2的方法，屏蔽转接卡第十一和第十二针脚

我打算先降驱动版本试试，不行的话就尝试一下这个神奇的方法，第一次听说……

**Comment by freeyoung** [comment]
> > 我的 x1c 6th 也出现了类似问题，黑苹果正常，但是 Windows 10 下面一连 WiFi 就死机。
> > I'm suffering from the same issue on my x1c 6th. It works fine in macOS but freezes Windows 10 whenever I connect to WiFi.
> 
> 可以尝试小新13pro上使用cs2的方法，屏蔽转接卡第十一和第十二针脚

参考了知乎这篇 https://zhuanlan.zhihu.com/p/111480447

但是实测无效，艰难地（手指有点粗）屏蔽了正面 11-12 针脚后，Windows 下只识别出蓝牙，没有无线网卡了。

**Comment by Calciferx** [comment]
> > > 我的 x1c 6th 也出现了类似问题，黑苹果正常，但是 Windows 10 下面一连 WiFi 就死机。
> > > I'm suffering from the same issue on my x1c 6th. It works fine in macOS but freezes Windows 10 whenever I connect to WiFi.
> > 
> > 
> > 可以尝试小新13pro上使用cs2的方法，屏蔽转接卡第十一和第十二针脚
> 
> 参考了知乎这篇 https://zhuanlan.zhihu.com/p/111480447
> 
> 但是实测无效，艰难地（手指有点粗）屏蔽了正面 11-12 针脚后，Windows 下只识别出蓝牙，没有无线网卡了。

感觉你有可能错误屏蔽了某些针脚，没有这两个针脚应该是不影响网卡识别的。上面说的更改usb充电的设置不管用吗

**Comment by freeyoung** [comment]
> > > > 我的 x1c 6th 也出现了类似问题，黑苹果正常，但是 Windows 10 下面一连 WiFi 就死机。
> > > > I'm suffering from the same issue on my x1c 6th. It works fine in macOS but freezes Windows 10 whenever I connect to WiFi.
> > > 
> > > 
> > > 可以尝试小新13pro上使用cs2的方法，屏蔽转接卡第十一和第十二针脚
> > 
> > 
> > 参考了知乎这篇 [zhuanlan.zhihu.com/p/111480447](https://zhuanlan.zhihu.com/p/111480447)
> > 但是实测无效，艰难地（手指有点粗）屏蔽了正面 11-12 针脚后，Windows 下只识别出蓝牙，没有无线网卡了。
> 
> 感觉你有可能错误屏蔽了某些针脚，没有这两个针脚应该是不影响网卡识别的。上面说的更改usb充电的设置不管用吗

Vantage 按你的说明改了 USB 充电的设置之后，多撑了几分钟，还是死机了，这次我仔细观察了一下，冻屏之后，CPU 风扇开始加快转速，然后屏幕显示的内容逐渐变黄、变暗乃至最后变黑。

屏蔽的 11-12 针脚请问是从哪边开始数起？我是从有缺口那一侧开始数的，即

`[4个][缺口][4个][缺口][跳过2个][屏蔽2个]`
