### ISSUE TITLE
this efi is not surppoted  for 10.14.1

### ISSUE THREAD

**Issue by kevinchain** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#17]
my device as same as errneist's. I use the efi ,it not good for 10.14.1.

**Comment by wu-hongjun** [comment]
If it doesn't work, try patch your own DSDT or see if there is anything you missed out.

**Comment by kevinchain** [comment]
"hid:legacy shim 2 " for a while ,and reboot.

**Comment by wu-hongjun** [comment]
> "hid:legacy shim 2 " for a while ,and reboot.

Try the Special Edition and see if you can get around.
