### ISSUE TITLE
BCM943602CS adapter and antenna

### ISSUE THREAD

**Issue by ghost** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#18]
Was going to put a DW1560 in, but has about half of the potential bandwidth as what comes with the laptop. Want to put something in there that is comparable, hence the BCM943602CS. 

Is there any issue with the back cover fitting even with the adapter?

My biggest question is regarding the antenna. I think the BCM943602CS is PCI-e and not NGFF, hence the adapter. That means the stock antenna already in the laptop on are NGFF. 

Will these work with the BCM943602CS? Do they all need to be replace? For the third antenna does it need to be NGFF specific or PCI-e?

**Comment by wu-hongjun** [comment]
Go look for a picture I published in the Bluetooth issue (it is in the closed issue). Not much is needed and it works fine for me for three months now.

**Comment by ghost** [comment]
Well, the pictures aren't really helping me figure out what third antenna to get, so I'm trying to figure that out. I did get the card, and adapter, and Wifi is working even without the third antenna (no bluetooth in Windows though... I know it won't work in macOS, but figured it would in Windows). The antenna already in there fit it fine. For the third antenna, I've bought 3 sets and none fit. Really not sure what I need, so was hoping to get help on that.

**Comment by wu-hongjun** [comment]
Nope. The M2 2230 socket has no usb channel for BT.
