### ISSUE TITLE
About Plugable USB3-6950-HDMI

### ISSUE THREAD

**Issue by wdde** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#20]
Hi Errr,
     我看到这两天更新了状态，外接显示器居然解决了，祝贺你！
在搜索这个适配器时，我看到了Plugable USBc-6950-HDMI，想知道为什么没选择这款，毕竟USB3太少了，而usb-c还闲着，这款usb-c适配器会正常工作吗？

I saw that you have updated the status in the past two days, and the external display has been solved. Congratulations!
When I searched for this adapter, I noticed the "Pluggable USBc-6950-HDMI", I wonder why you didn't choose this. for X1E, USB3 ports is too few,  usb-c is almost idle. Will this usb-c adapter work normally?

**Comment by wu-hongjun** [comment]
Not sure for USB-C. It could work in theory (As long as it uses DisplayLink chip), but I don't want to risk it. Also I need to plug both of the USB-C.

不确定 理论上可以 因为只要是用DisplayLink6950（或者6000系芯片）大概都是可以走USB通道输出的。但是我第一懒得冒万一这玩意走的是主板的显示接口的风险第二是我的USB-C插满了……

**Comment by wu-hongjun** [comment]
If you bought the USB-C one, tell us how it goes plz :)

**Comment by carlaiau** [comment]
@Errrneist I have one in the mail, and will update when it's here. Currently I'm running Catalina on Gen 2 X1E, unfortunately the second generation has whitelist so I am going to go with a USB dongle for WiFi

**Comment by caiisen** [comment]
> @Errrneist I have one in the mail, and will update when it's here. Currently I'm running Catalina on Gen 2 X1E, unfortunately the second generation has whitelist so I am going to go with a USB dongle for WiFi

does  USBc-6950-HDMI work?
