### ISSUE TITLE
Fans and sensors issue

### ISSUE THREAD

**Issue by frankwangyufei** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#22]
Did you get fans showing up? While mine sometimes spin, I cannot see them in iStat or other software. 

Also, my temperature sensors seems a bit odd. When charging in mac, it will say 60C even when I can feel it getting really hot. A quick restart into windows have HWmonitor showing 80C and fans will spin like crazy (maybe it heats up during reboot idk).

I am not sure what to provide so sorry for the vague description

**Comment by frankwangyufei** [comment]
My x1-extreme is model 20MFCTO1WW with an i7-8750h. Do you think this is causing the issue?

**Comment by wu-hongjun** [comment]
I don’t have fan issues. Maybe try configure and patch your own DSDT?

**Comment by frankwangyufei** [comment]
Do you mean you can see the fans in iStat and Macs Fan Control?

**Comment by frankwangyufei** [comment]
I am currently trying to patch DSDT, will update if there is progress

**Comment by wu-hongjun** [comment]
I don't use iStat since I don't have fan problems.

**Comment by gfoury** [comment]
By the way, you should all be using https://github.com/sicreative/VoltageShift to lower the CPU/GPU core voltage. It helps temperature and noise *a lot*.

On mine, I have CPU/cache set to -100mV, and GPU set to -25mV.

**Comment by gfoury** [comment]
I have no modifications to my DSDT.aml except for the X220 battery mod. 

I have the FakeSMC plugins installed:

```
/Volumes/EFI/EFI/CLOVER/kexts/Other/FakeSMC.kext/Contents/PlugIns $ ls
FakeSMC_ACPISensors.kext  FakeSMC_GPUSensors.kext  FakeSMC_SMMSensors.kext
FakeSMC_CPUSensors.kext   FakeSMC_LPCSensors.kext
```

Here's what I see in iStat Menus:
![Screen Shot 2019-05-05 at 5 25 47 PM copy](https://user-images.githubusercontent.com/16920172/57200600-0bf83100-6f5c-11e9-8a8f-7bb9e9d74216.png)

and in HWMonitor:

![Screen Shot 2019-05-05 at 5 30 58 PM](https://user-images.githubusercontent.com/16920172/57200604-187c8980-6f5c-11e9-9923-fbec0f26a2bc.png)

**Comment by frankwangyufei** [comment]
Interesting, voltage shift did not work for me before, will try it later

**Comment by frankwangyufei** [comment]
I tried voltage shift but even with SIP disabled and file permission, it still show no output.
Did you do any workaround?

**Comment by frankwangyufei** [comment]
nevermind, it turns out the issue is with the signing issue with xcode. Now it works perfectly 😄 🎉
