### ISSUE TITLE
Pinout for the smartcard ribbon cable?

### ISSUE THREAD

**Issue by billylindeman** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#23]
I see the custom hacked adapter for the smartcard ribbon cable and was curious if you could add a pinout description for the FPC connector. It seems like its a usb port?

**Comment by wu-hongjun** [comment]
It is a USB port, but I don't know the pinout. I just try every single combination until it worked.

**Comment by wu-hongjun** [comment]
https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/11#issuecomment-494201071 This might answer your question.
