### ISSUE TITLE
Question: Lenovo Thunderbolt 3 Workstation dock compatibility?

### ISSUE THREAD

**Issue by danieldunderfelt** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#24]
Hi! I'm using a Thinkpad X1 Extreme for development work and I'm investigating how well it handles being a Hackintosh. I bought a TB3 Workstation dock with the laptop, and was wondering if anyone has tried the dock with a hackintoshed X1 Extreme. I read about eGPU problems over TB3, but I would not be running one of those. I currently run Linux, and the dock works perfectly.

**Comment by wu-hongjun** [comment]
No idea. Please try and tell us the result :)

**Comment by wu-hongjun** [comment]
> Hi! I'm using a Thinkpad X1 Extreme for development work and I'm investigating how well it handles being a Hackintosh. I bought a TB3 Workstation dock with the laptop, and was wondering if anyone has tried the dock with a hackintoshed X1 Extreme. I read about eGPU problems over TB3, but I would not be running one of those. I currently run Linux, and the dock works perfectly.

I have a gigabyte AORUS Gaming Box 1080 but because NVIDIA cards are not currently supported I cannot test TB3 functionality on that. If you happen to get TB3 working please please let us know it is really important!!!

**Comment by wu-hongjun** [comment]
> Hi! I'm using a Thinkpad X1 Extreme for development work and I'm investigating how well it handles being a Hackintosh. I bought a TB3 Workstation dock with the laptop, and was wondering if anyone has tried the dock with a hackintoshed X1 Extreme. I read about eGPU problems over TB3, but I would not be running one of those. I currently run Linux, and the dock works perfectly.

Did you get a chance to try it out?

**Comment by danieldunderfelt** [comment]
No, not yet. I actually took the laptop back to the shop, gonna wait for the next generation. Linux works fine for me, so I'm not sure if I want to try hackintoshing anyway. This issue was just some exploratory research.

**Comment by wu-hongjun** [comment]
Oh okay that's cool too. The 2nd generation is out though so you can get one pretty soon.
