### ISSUE TITLE
Overheat after plugged into AC

### ISSUE THREAD

**Issue by eunrui** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#26]
您有注意到接通电源后发热的问题吗？
键盘左侧和右侧都很烫，但是cpu温度显示50度，这在windows下是没有发生的。
而且nvme固态也比windows下高出20度。
摸起来真的很烫，担心会出问题，希望得到您的回答，感谢^
--------------------------------------------------
ps:担心翻译器翻译的会出差错只好用中文了，抱歉。

![屏幕快照 2019-05-25 12 18 34](https://user-images.githubusercontent.com/49180440/58364513-33517680-7ee8-11e9-8482-009ebaa109f2.png)

**Comment by wu-hongjun** [comment]
You might need to patch our own DSDT.
Also, post in English next time. Please read “Issue Report” section in Readme.MD.

**Comment by eunrui** [comment]
> 您可能需要修补我们自己的DSDT。
> 另外，下次用英文发帖。请阅读Readme.MD中的“问题报告”部分。

thanks

**Comment by darkal** [comment]
> ## 您有注意到接通电源后发热的问题吗？
> 键盘左侧和右侧都很烫，但是cpu温度显示50度，这在windows下是没有发生的。
> 而且nvme固态也比windows下高出20度。
> 摸起来真的很烫，担心会出问题，希望得到您的回答，感谢^
> ps:担心翻译器翻译的会出差错只好用中文了，抱歉。
> 
> ![屏幕快照 2019-05-25 12 18 34](https://user-images.githubusercontent.com/49180440/58364513-33517680-7ee8-11e9-8482-009ebaa109f2.png)

是的，MacOS系统下风扇策略比较保守，的确温度比windows高，但是风扇低负载下就很少转了，我已经这样用了快半年了，没啥问题

**Comment by wdde** [comment]
我很期待有人能开发一个哪怕很简陋的让风扇保持旋转的程序，只要风扇转，温度就会降下来，但是我觉得自己在做梦

**Comment by wu-hongjun** [comment]
> 我很期待有人能开发一个哪怕很简陋的让风扇保持旋转的程序，只要风扇转，温度就会降下来，但是我觉得自己在做梦

你天天放在腿上用吗...？老实说我还蛮喜欢风扇不转的...

**Comment by eunrui** [comment]
> > 我很期待有人能开发一个哪怕很简陋的让风扇保持旋转的程序，只要风扇转，温度就会降下来，但是我觉得自己在做梦
> 
> 你天天放在腿上用吗......？老实说我还蛮喜欢风扇不转的...

您好作者~ 想请教一下屏幕刷新率在哪里显示呀 显示器设置里没有找到
![屏幕快照 2019-06-14 上午12 15 45](https://user-images.githubusercontent.com/49180440/59449419-94aa9c80-8e39-11e9-97be-85b463882d54.png)

**Comment by wu-hongjun** [comment]
> > > 我很期待有人能开发一个哪怕很简陋的让风扇保持旋转的程序，只要风扇转，温度就会降下来，但是我觉得自己在做梦
> > 
> > 
> > 你天天放在腿上用吗......？老实说我还蛮喜欢风扇不转的...
> 
> 您好作者~ 想请教一下屏幕刷新率在哪里显示呀 显示器设置里没有找到
> ![屏幕快照 2019-06-14 上午12 15 45](https://user-images.githubusercontent.com/49180440/59449419-94aa9c80-8e39-11e9-97be-85b463882d54.png)

内屏好像不行噢 外屏可以...

**Comment by eunrui** [comment]
> > > > 我很期待有人能开发一个哪怕很简陋的让风扇保持旋转的程序，只要风扇转，温度就会降下来，但是我觉得自己在做梦
> > > 
> > > 
> > > 你天天放在腿上用吗......？老实说我还蛮喜欢风扇不转的...
> > 
> > 
> > 您好作者~ 想请教一下屏幕刷新率在哪里显示呀 显示器设置里没有找到
> > ![屏幕快照 2019-06-14 上午12 15 45](https://user-images.githubusercontent.com/49180440/59449419-94aa9c80-8e39-11e9-97be-85b463882d54.png)
> 
> 内屏好像不行噢 外屏可以...

晓得咯 谢谢^^
