### ISSUE TITLE
cannot get hibernate really work

### ISSUE THREAD

**Issue by wdde** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#27]
hibernation can't really work,  consume more than 1% of electricity per hour in battery mode
Found that "pmset -g" returns no "autopoweroff"  in the results, hibernate mode 3 can not be effective, the system is just sleep, no hibernation, and can not automatically shut down under hibernate mode=25. Currently hiberationfixup.kext already uses the latest version in the 10.14.3 directory. Any suggestions? Google can hardly find information about autopoweroff missing.

-> % pmset -g
System-wide power settings:
 DestroyFVKeyOnStandby		1
Currently in use:
 standbydelaylow      10800
 standby              1
 womp                 0
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             1
 gpuswitch            2
 networkoversleep     0
 halfdim              1
 standbydelayhigh     86400
 sleep                0
 hibernatemode        3
 disksleep            10
 ttyskeepawake        1
 displaysleep         10
 tcpkeepalive         1
 highstandbythreshold 50
 lidwake              1

**Comment by wu-hongjun** [comment]
What do you exactly mean hibernation? Does that mean you close the lid? I usually just close the lid as I go, and I don't feel a significant battery drain...try update EFI to v10.14.5.1.0?

**Comment by wdde** [comment]
Close the lid, or click on the apple button then click sleep, the system should enter a low energy state, I remember that after I built the hackintosh, the battery only drain 1 to 5%  per night , but now, obviously more than 10%, I removed Bluetooth USB adapter the result is the same. What should be caused? I checked out the tonymacx86  try to  find some help for this but no luck.  I don't know how to troubleshoot the fault.
In addition, if  upgrade to 10.14.5, which documents should you refer to? Also, what is the BIOS version of your X1E?

**Comment by wu-hongjun** [comment]
> Close the lid, or click on the apple button then click sleep, the system should enter a low energy state, I remember that after I built the hackintosh, the battery only drain 1 to 5% per night , but now, obviously more than 10%, I removed Bluetooth USB adapter the result is the same. What should be caused? I checked out the tonymacx86 try to find some help for this but no luck. I don't know how to troubleshoot the fault.
> In addition, if upgrade to 10.14.5, which documents should you refer to? Also, what is the BIOS version of your X1E?

I mean I just released a EFI for 10.14.5. Also BIOS 1.21

**Comment by wdde** [comment]
初步结果：耗电问题解决了，涉及了组合设置 ，目前还不清楚具体是哪个设置起了作用
pm 18:00~am 9:30 电池电量下降2% 

pm 18:00~am 9:30，Battery power dropped by 2%
The power consumption problem has been solved, and the combination settings are involved. It is still unclear which setting which setting is effective.

1、disable proximitywake https://www.reddit.com/r/hackintosh/comments/9jfa8w/mojave_new_pmset_options/
2、disable TCPKeepAliveDuringSleep  
https://apple.stackexchange.com/questions/253776/macbook-pro-13-with-retina-display-consumes-10-battery-overnight-with-the-lid-c

**Comment by wdde** [comment]
> > Close the lid, or click on the apple button then click sleep, the system should enter a low energy state, I remember that after I built the hackintosh, the battery only drain 1 to 5% per night , but now, obviously more than 10%, I removed Bluetooth USB adapter the result is the same. What should be caused? I checked out the tonymacx86 try to find some help for this but no luck. I don't know how to troubleshoot the fault.
> > In addition, if upgrade to 10.14.5, which documents should you refer to? Also, what is the BIOS version of your X1E?
> 
> I mean I just released a EFI for 10.14.5. Also BIOS 1.21

First of all, thank you for updating this project. I have seen that the new issue of zysuper project has not been tracked.

Regarding the upgrade, I saw a lot of people complaining that after upgrading bios, hackintosh no longer works. After all, it involves changes in bios. I plan to upgrade bios from 1.18 to 1.19, but I don't know if it will make the system unavailable.
Also, I am currently running on 10.14.3, if I upgrade to 10.14.5, is the following procedure correct? 
1. Under macos, upgrade online to 10.14.5 via apple air push.
2. Overwrite the current efi files in the EFI partition with the 10.14.5 EFI corresponding to your github project.
3, view / L / E, use the new kext coverage corresponding to the github project, execute kextcache -i
4, restart

Are there any problems with these steps?  What's your suggestion ? Restore time machine backup after a new installation?
 thank you very much!

**Comment by wu-hongjun** [comment]
> > > Close the lid, or click on the apple button then click sleep, the system should enter a low energy state, I remember that after I built the hackintosh, the battery only drain 1 to 5% per night , but now, obviously more than 10%, I removed Bluetooth USB adapter the result is the same. What should be caused? I checked out the tonymacx86 try to find some help for this but no luck. I don't know how to troubleshoot the fault.
> > > In addition, if upgrade to 10.14.5, which documents should you refer to? Also, what is the BIOS version of your X1E?
> > 
> > 
> > I mean I just released a EFI for 10.14.5. Also BIOS 1.21
> 
> First of all, thank you for updating this project. I have seen that the new issue of zysuper project has not been tracked.
> 
> Regarding the upgrade, I saw a lot of people complaining that after upgrading bios, hackintosh no longer works. After all, it involves changes in bios. I plan to upgrade bios from 1.18 to 1.19, but I don't know if it will make the system unavailable.
> Also, I am currently running on 10.14.3, if I upgrade to 10.14.5, is the following procedure correct?
> 
> 1. Under macos, upgrade online to 10.14.5 via apple air push.
> 2. Overwrite the current efi files in the EFI partition with the 10.14.5 EFI corresponding to your github project.
>    3, view / L / E, use the new kext coverage corresponding to the github project, execute kextcache -i
>    4, restart
> 
> Are there any problems with these steps? What's your suggestion ? Restore time machine backup after a new installation?
> thank you very much!

If there is no real need to upgrade BIOS I'd say just DON'T upgrade it. Stay in what works. I did not upgrade to 10.14.5, my entire laptop crashed so I had to do a fresh install. Yours might differ, but have a try on V10.14.5 on your existing 10.14.3 before you update system. Definately swap EFI BEFORE you install update since I remember when I updated to 10.14.4 from 10.14.3, the old EFI did not work.

**Comment by wdde** [comment]
Thank you for your suggestion, I decided not to upgrade for the time being, 10.14.3 should not be outdated. At present, this Macintosh has almost no problem except hot. The connection of BT mouse loss after Bluetooth wake-up is solved too. 
    What I am most dissatisfied with is the system operating temperature. Obviously, only when the hwmonitor temperature exceeds 60 degrees Celsius, the cooling fan will rotate. When the macos is at low load, the CPU temperature is about 50 degrees Celsius, but I think the temperature detection is not accurate. The 50 degrees Celsius under macos is obviously hotter than 60 degrees that under windows10 if I touch the area on the left side of the TAB key, it can be clearly felt, I checked the google and tonymacx86, trying to find a more accurate temperature measurement program, but did not find, I hope that the cooling fan is more active, just like MBP is always in an active cooling state,, but Lenovo does not provide such a BIOS. 
     Anyway, thank you guys, without you, we can't enjoy high quality hackintosh.

**Comment by oreziam** [comment]
> > > 关闭盖子，或者点击苹果按钮然后点击睡眠，系统应该进入低能量状态，我记得在我制作了hackintosh之后，电池每晚仅消耗1到5％，但现在，显然超过10 ％，我删除蓝牙USB适配器的结果是一样的。应该引起什么？我检查了tonymacx86尝试找到一些帮助，但没有运气。我不知道如何排除故障。
> > > 另外，如果升级到10.14.5，你应该参考哪些文件？另外，X1E的BIOS版本是什么？
> > 
> > 
> > 我的意思是我刚刚发布了10.14.5的EFI。还有BIOS 1.21
> 
> 首先，感谢您更新此项目。我已经看到zysuper项目的新问题没有被跟踪。
> 
> 关于升级，我看到很多人抱怨升级BIOS后，hackintosh不再有效。毕竟，它涉及到bios的变化。我计划将BIOS从1.18升级到1.19，但我不知道它是否会使系统不可用。
> 另外，我目前正在运行10.14.3，如果我升级到10.14.5，以下程序是否正确？
> 
> 1. 在macos下，通过apple air push在线升级到10.14.5。
> 2. 使用与您的github项目对应的10.14.5 EFI覆盖EFI分区中的当前efi文件。
>    3，查看/ L / E，使用与github项目对应的新kext覆盖，执行kextcache -i 
>    4，重启
> 
> 这些步骤有问题吗？你的建议是什么？新安装后还原时间机器备份？
> 非常感谢你！

我使用了这个方法，但1小时耗电还是会有超过5%
