### ISSUE TITLE
need more information re wifi moduel

### ISSUE THREAD

**Issue by pzoltowski** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#28]
Can you share more information regarding wifi module?
1) what's the difference between  BCM94360CS2 and BRCM943602CS?
2) Does it have to be original wifi module from apple devices or any replacement that has the same chips? I just checked amazon and its seems they have only some replacements unless some have better idea where to buy them
3) Do both of them require adapter? Can you share more information about adapter or maybe even picture? I noticed on aliexpress there are still different m.2 adapters and some seems long (2280?) so they might not fit into laptop? What's the best place to buy those adapters?

**Comment by wu-hongjun** [comment]
Both require adapter. If you do research they are two different cards. They are from apple. eBay or taobao.
