### ISSUE TITLE
The cursor jumping when typing.

### ISSUE THREAD

**Issue by wdde** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#29]
There is a strange problem that bothers me. When I typing in some text editor, the cursor will jump to other positions, such as the previous/next line, such as forward or backward characters, and I'm sure I did not touch the touchpad,. you know, when I want to type a lot, this issue will drive me crazy.
I currently use the multi-gesture VoodooPS2Controller.kex, and the red dot is invalid. Trying to change to the original version does not improve this symptom.
Any suggestions? thanks a lot.

有个奇怪的问题在困扰我，当进行文字编辑的时候，光标会跳到其它位置，比如上一行，比如向前或向后几个字符，而我没有碰到触摸版，在大量打字的时候，会把我逼疯掉。
我目前使用多手势的VoodooPS2Controller.kex，红点无效。尝试更换到原始版本，也不能改善这个症状。

**Comment by wu-hongjun** [comment]
我自己用的这个版本是红点有效的啊？你可以试试我的VoodooPS2，我的没有这个问题。

**Comment by wdde** [comment]
> 我自己用的这个版本是红点有效的啊？你可以试试我的VoodooPS2，我的没有这个问题。
 你的VoodooPS2既支持触摸板多手势，又支持红点，是这样吗？那可太好了，不过我发现，在iterm2里，打字很少会飘移，几乎没什么印象，在文字编辑器里就容易飘移，难道是清歌输入法的问题？

**Comment by wu-hongjun** [comment]
> 我自己用的这个版本是红点有效的啊？你可以试试我的VoodooPS2，我的没有这个问题。
> 你的VoodooPS2既支持触摸板多手势，又支持红点，是这样吗？那可太好了，不过我发现，在iterm2里，打字很少会飘移，几乎没什么印象，在文字编辑器里就容易飘移，难道是清歌输入法的问题？

不支持手势。
