### ISSUE TITLE
Audio problem after waking from hibernation

### ISSUE THREAD

**Issue by flymin** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#31]
I am using the release version 10.14.4-1.1. However, there is no sound after waking from hibernation, and kill coreaudio will not work. Only restart can fix it. Is there any solutions or some updates in the following version I could benefit from?

我用10.14.4-1.1装好后，睡眠唤醒会没有声音，在任务中重新启动coreaudio也没效果，只能重启。请问有什么解决办法吗？

**Comment by eunrui** [comment]
https://bbs.feng.com/forum.php?mod=viewthread&tid=7686329&page=1
这个可以帮助您 亲测有效 只不过每次睡眠唤醒需要手动修复

**Comment by flymin** [comment]
> https://bbs.feng.com/forum.php?mod=viewthread&tid=7686329&page=1
> 这个可以帮助您 亲测有效 只不过每次睡眠唤醒需要手动修复

有效！感谢
另外我试了一些情况，发现只有在打开新的播放应用时会出问题，如果是睡眠之前就已经打开的软件则不会有问题。而且，如果打开的时候有其他软件在播放声音也会避免这个问题。猜测问题在应用注册播放服务的时候出的毛病，知识有限。

it works!
BTW, I have been tried several situations and found out that such problem only occur when opening a new sound-play app. Using those have been opened before hibernation is fine. Besides, if there is sound being played when opening a new app, it works fine, too.

**Comment by eunrui** [comment]
> > https://bbs.feng.com/forum.php?mod=viewthread&tid=7686329&page=1 
> > 这个可以帮助您亲测有效只不过每次睡眠唤醒需要手动修复
> 
> 有效！感谢
> 另外我试了一些情况，发现只有在打开新的播放应用时会出问题，如果是睡眠之前就已经打开的软件则不会有问题。而且，如果打开的时候有其他软件在播放声音也会避免这个问题。猜测问题在应用注册播放服务的时候出的毛病，知识有限。
> 
> 有用！
> 顺便说一句，我已经尝试了几种情况，并发现只有在打开一个新的声音播放应用程序时才会出现这样的问题。在休眠状态良好之前使用这些已经打开。此外，如果在打开新应用程序时播放声音，它也可以正常工作。

这个倒是没有测试过，反正每次睡眠完都不好使了，建议更新<https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.14.5.1.3>，Errrneist修复了他~

**Comment by flymin** [comment]
@eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist 

To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.

**Comment by eunrui** [comment]
> @eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist
> 
> To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.

em...我升完倒是好用了，没失效，作者升到10.15了貌似也没法找到问题了吧 - -

**Comment by wu-hongjun** [comment]
> > @eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist
> > To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.
> 
> em...我升完倒是好用了，没失效，作者升到10.15了貌似也没法找到问题了吧 - -

唔 理论上这个10.15是向下兼容的……？

**Comment by wu-hongjun** [comment]
> > @eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist
> > To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.
> 
> em...我升完倒是好用了，没失效，作者升到10.15了貌似也没法找到问题了吧 - -

以及 Catalina是真的香啊

**Comment by eunrui** [comment]
> > > @eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist
> > > To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.
> > 
> > 
> > em...我升完倒是好用了，没失效，作者升到10.15了貌似也没法找到问题了吧 - -
> 
> 以及 Catalina是真的香啊

还不错 除了新下的软件要手动拽到launchpad 1080P开启hidpi不起作用了 其他bug倒没碰到 
对了 风扇的策略是变了吗 现在65度才会开始转 好烫啊..

**Comment by wu-hongjun** [comment]
> > > > @eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist
> > > > To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.
> > > 
> > > 
> > > em...我升完倒是好用了，没失效，作者升到10.15了貌似也没法找到问题了吧 - -
> > 
> > 
> > 以及 Catalina是真的香啊
> 
> 还不错 除了新下的软件要手动拽到launchpad 1080P开启hidpi不起作用了 其他bug倒没碰到
> 对了 风扇的策略是变了吗 现在65度才会开始转 好烫啊..

我的风扇呼呼呼的转……launchpad的问题我也遇到了，hidpi内屏没啥感觉……

**Comment by eunrui** [comment]
> > > > > @eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist
> > > > > To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.
> > > > 
> > > > 
> > > > em...我升完倒是好用了，没失效，作者升到10.15了貌似也没法找到问题了吧 - -
> > > 
> > > 
> > > 以及 Catalina是真的香啊
> > 
> > 
> > 还不错 除了新下的软件要手动拽到launchpad 1080P开启hidpi不起作用了 其他bug倒没碰到
> > 对了 风扇的策略是变了吗 现在65度才会开始转 好烫啊..
> 
> 我的风扇呼呼呼的转……launchpad的问题我也遇到了，hidpi内屏没啥感觉……

em.. pb3/v10.15.0.1.1版本的applealc睡眠唤醒后不工作了 要手动修复上了 您遇到了吗 上次修复后都没遇到过了

**Comment by wu-hongjun** [comment]
> > > > > > @eumrui 忘了说明，[以上情况](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984)测试环境是v10.14.5.1.3，看到作者的release记录之后第一时间更新了，但是情况就是这样。此处是不是应该 @Errrneist
> > > > > > To add, [the situation](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/31#issuecomment-508974984) l claimed occurs in v10.14.5.1.3.
> > > > > 
> > > > > 
> > > > > em...我升完倒是好用了，没失效，作者升到10.15了貌似也没法找到问题了吧 - -
> > > > 
> > > > 
> > > > 以及 Catalina是真的香啊
> > > 
> > > 
> > > 还不错 除了新下的软件要手动拽到launchpad 1080P开启hidpi不起作用了 其他bug倒没碰到
> > > 对了 风扇的策略是变了吗 现在65度才会开始转 好烫啊..
> > 
> > 
> > 我的风扇呼呼呼的转……launchpad的问题我也遇到了，hidpi内屏没啥感觉……
> 
> em.. pb3/v10.15.0.1.1版本的applealc睡眠唤醒后不工作了 要手动修复上了 您遇到了吗 上次修复后都没遇到过了

目前还没有遇到

**Comment by wdde** [comment]
I met this issue few days ago, replace the applealc kext with newer version and set the layout id to 11 should solve the problem.

**Comment by flymin** [comment]
> I met this issue few days ago, replace the applealc kext with newer version and set the layout id to 11 should solve the problem.

Thank you for your announcement. However, this is a solved issue. You can find my solution in [issue #40](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/40), or just use more updated release version in this repo, which is using another layout.

**Comment by wu-hongjun** [comment]
It seems like everyone’s laptop is slightly different. Pick the AppleALc/Layout ID that works for you.
