### ISSUE TITLE
Thermal Issues / 散热的问题

### ISSUE THREAD

**Issue by toread** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#32]
cpu温度一直是 60°  但是风扇不工作，导致了整体温度都很高 .
windwos 不存在这个问题 ，风扇是工作的。
![Uploading 企业微信截图_15630922198763.png…]()

**Comment by toread** [comment]
![企业微信截图_15630922198763](https://user-images.githubusercontent.com/6276786/61186272-f1e27980-a695-11e9-94d7-f18bdcefaa0f.png)

**Comment by wu-hongjun** [comment]
我的Win温度很高 macOS巨安静频率也很合理 一般都是需要自己配置DSDT。

**Comment by wu-hongjun** [comment]
> cpu温度一直是 60° 但是风扇不工作，导致了整体温度都很高 .
> windwos 不存在这个问题 ，风扇是工作的。

而且 macOS对风扇的控制相对保守（目前好多人都觉得有点保守不过还没什么解决办法）不过我觉得吧不呼呼呼吹我还蛮喜欢的……一般我的本子稳定在55度左右 风扇不转或者听不见声音 我都快忘了风扇这回事了……只有回Win跑3D应用打游戏才会想起来还有个风扇在转……

**Comment by ColeXJ** [comment]
我也发现了这个问题，我没有听到风扇的声音，甚至我怀疑风扇根本就没有运转。我轻量级使用一会，发现会非常烫，已经影响到使用感受了。感觉如果重度使用它可能会死机。

**Comment by wu-hongjun** [comment]
> 我也发现了这个问题，我没有听到风扇的声音，甚至我怀疑风扇根本就没有运转。我轻量级使用一会，发现会非常烫，已经影响到使用感受了。感觉如果重度使用它可能会死机。

重度使用我的是会高速转的 只是阈值比较高

**Comment by ColeXJ** [comment]
我直接用的你的EFI，非常感谢你对x1E这款机型的贡献，让我们能轻松的装上苹果系统。我对黑苹果的dsdt这些设置一窍不通。我想问一下，如果我们是同样的机型（x1E 4K屏），我需要设置自己的dsdt才能解决这个风扇的问题吗？ 我现在准备测试一下，我是否在重度使用的时候会触发风扇运转。

**Comment by wu-hongjun** [comment]
> 我直接用的你的EFI，非常感谢你对x1E这款机型的贡献，让我们能轻松的装上苹果系统。我对黑苹果的dsdt这些设置一窍不通。我想问一下，如果我们是同样的机型（x1E 4K屏），我需要设置自己的dsdt才能解决这个风扇的问题吗？ 我现在准备测试一下，我是否在重度使用的时候会触发风扇运转。

大概吧，我的DSDT用的是zysuper的居然好使，就没有自己配置了。

**Comment by ColeXJ** [comment]
我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？

**Comment by wu-hongjun** [comment]
> 我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？

是的

**Comment by wu-hongjun** [comment]
> 我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？

以及虽然可能还是没用你可以试试看10.15.0.1.0（记得备份EFI）

**Comment by toread** [comment]
网上买了一个黑苹果的 无线网卡USB 安装以后 苹果也起不来了 黑屏了

**Comment by toread** [comment]
现在又起来了

**Comment by toread** [comment]
> 我的Win温度很高 macOS巨安静频率也很合理 一般都是需要自己配置DSDT。
如何配置DSDT 有链接的教程么,本来打算改风扇的,但是不识别风扇传感器

**Comment by eunrui** [comment]
> > 我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？
> 
> 以及虽然可能还是没用你可以试试看10.15.0.1.0（记得备份EFI）

Have u updated Catalina 10.15 Beta4 yet?
您更新了Beta4了吗

**Comment by wu-hongjun** [comment]
> > > 我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？
> > 
> > 
> > 以及虽然可能还是没用你可以试试看10.15.0.1.0（记得备份EFI）
> 
> Have u updated Catalina 10.15 Beta4 yet?
> 您更新了Beta4了吗

I’m on public beta 2

我是PB2，不在DB

**Comment by wu-hongjun** [comment]
> > > 我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？
> > 
> > 
> > 以及虽然可能还是没用你可以试试看10.15.0.1.0（记得备份EFI）
> 
> Have u updated Catalina 10.15 Beta4 yet?
> 您更新了Beta4了吗

更新PB3了 1.0版本还是好使

**Comment by eunrui** [comment]
> > > > 我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？
> > > 
> > > 
> > > 以及虽然可能还是没用你可以试试看10.15.0.1.0（记得备份EFI）
> > 
> > 
> > Have u updated Catalina 10.15 Beta4 yet?
> > 您更新了Beta4了吗
> 
> 更新PB3了 1.0版本还是好使

nb! pb2总是随机的将我的输入法弄没或者音量静音不能调节 晚上到家我试试看 感谢！

**Comment by wu-hongjun** [comment]
> > > > > 我现在使用的是你的 14.5的1.3版本，请问这个版本的dsdt也是来自zysuper的吗？
> > > > 
> > > > 
> > > > 以及虽然可能还是没用你可以试试看10.15.0.1.0（记得备份EFI）
> > > 
> > > 
> > > Have u updated Catalina 10.15 Beta4 yet?
> > > 您更新了Beta4了吗
> > 
> > 
> > 更新PB3了 1.0版本还是好使
> 
> nb! pb2总是随机的将我的输入法弄没或者音量静音不能调节 晚上到家我试试看 感谢！

我的PB2没有这个问题哎我其实还没遇到任何问题除了photos偶尔会crash

**Comment by eunrui** [comment]
> cpu温度一直是 60° 但是风扇不工作，导致了整体温度都很高 .
> windwos 不存在这个问题 ，风扇是工作的。

升级了bios后 舒服了 稳定在50度 键盘两侧也不那么烫了 温的 风扇终于转起来了。。

**Comment by wu-hongjun** [comment]
> > cpu温度一直是 60° 但是风扇不工作，导致了整体温度都很高 .
> > windwos 不存在这个问题 ，风扇是工作的。
> 
> 升级了bios后 舒服了 稳定在50度 键盘两侧也不那么烫了 温的 风扇终于转起来了。。

你版本多少啊

**Comment by eunrui** [comment]
> > > cpu温度一直是 60° 但是风扇不工作，导致了整体温度都很高 .
> > > windwos 不存在这个问题 ，风扇是工作的。
> > 
> > 
> > 升级了bios后 舒服了 稳定在50度 键盘两侧也不那么烫了 温的 风扇终于转起来了。。
> 
> 你版本多少啊

和您的一样啊 以前1.17.. 不到65都不转的

**Comment by wu-hongjun** [comment]
阔以

**Comment by wdde** [comment]
我最近也在测试bios升级对风扇行为的影响 ，1.18～1.21都升级过，Mac下都是60以上，估计65度才会开始主动旋转，而有一点很明显: Mac下测得的温度，如果按60度进行比较，windows下的60度并没有很烫，而Mac下的60度，左手边（tab/capslock/~这些键左边）明显很烫。
看了eumrui的回贴，我也想升级一下试试，只不过，一旦升级1.23，就再也不能降低到低版本了（与UEFI有关）。

**Comment by wu-hongjun** [comment]
> 我最近也在测试bios升级对风扇行为的影响 ，1.18～1.21都升级过，Mac下都是60以上，估计65度才会开始主动旋转，而有一点很明显: Mac下测得的温度，如果按60度进行比较，windows下的60度并没有很烫，而Mac下的60度，左手边（tab/capslock/~这些键左边）明显很烫。
> 看了eumrui的回贴，我也想升级一下试试，只不过，一旦升级1.23，就再也不能降低到低版本了（与UEFI有关）。

风扇还行吧我觉得，但是睡眠漏电问题在PB4好像修复了

**Comment by darkal** [comment]
升级1.23  bios 后日常使用温度明显低了

**Comment by wdde** [comment]
> 升级1.23 bios 后日常使用温度明显低了

太棒了！尤其是得到老司机的确认！！感谢你们的实践和分享！！

**Comment by wu-hongjun** [comment]
> > 升级1.23 bios 后日常使用温度明显低了
> 
> 太棒了！尤其是得到老司机的确认！！感谢你们的实践和分享！！

确认

**Comment by wdde** [comment]
> > 我最近也在测试bios升级对风扇行为的影响 ，1.18～1.21都升级过，Mac下都是60以上，估计65度才会开始主动旋转，而有一点很明显: Mac下测得的温度，如果按60度进行比较，windows下的60度并没有很烫，而Mac下的60度，左手边（tab/capslock/~这些键左边）明显很烫。
> > 看了eumrui的回贴，我也想升级一下试试，只不过，一旦升级1.23，就再也不能降低到低版本了（与UEFI有关）。
> 
> 风扇还行吧我觉得，但是睡眠漏电问题在PB4好像修复了

  睡眠漏电是什么？是掉电太多吗？我前段时间测试过，关闭powernap和无线网络的情况下，睡眠耗电一整晚，才掉2%，多次验证过。如果开启powernap，将下降6%左右，这应该非常接近白苹果了。

**Comment by wdde** [comment]
> > > 升级1.23 bios 后日常使用温度明显低了
> > 
> > 
> > 太棒了！尤其是得到老司机的确认！！感谢你们的实践和分享！！
> 
> 确认

刚刚升级了1.23，fan spin的温度阈值确实降低了很多，目前还不知道什么 温度才会停转 >.<

**Comment by wu-hongjun** [comment]
> > > 我最近也在测试bios升级对风扇行为的影响 ，1.18～1.21都升级过，Mac下都是60以上，估计65度才会开始主动旋转，而有一点很明显: Mac下测得的温度，如果按60度进行比较，windows下的60度并没有很烫，而Mac下的60度，左手边（tab/capslock/~这些键左边）明显很烫。
> > > 看了eumrui的回贴，我也想升级一下试试，只不过，一旦升级1.23，就再也不能降低到低版本了（与UEFI有关）。
> > 
> > 
> > 风扇还行吧我觉得，但是睡眠漏电问题在PB4好像修复了
> 
> 睡眠漏电是什么？是掉电太多吗？我前段时间测试过，关闭powernap和无线网络的情况下，睡眠耗电一整晚，才掉2%，多次验证过。如果开启powernap，将下降6%左右，这应该非常接近白苹果了。

PB3一小时掉10%
