### ISSUE TITLE
Issue with booting with 64G RAM / 64G内存引导问题

### ISSUE THREAD

**Issue by oreziam** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#34]
我是三星32G DDR4 2666内存*2，单根可以引导，两根不行。注入内存为16*4，也不行（该方法在冥王峡谷 NUC上成功）。

**Comment by wu-hongjun** [comment]
> 我是三星32G DDR4 2666内存_2，单根可以引导，两根不行。注入内存为16_4，也不行（该方法在冥王峡谷 NUC上成功）。

好奢侈的烦恼啊… 这个我也没遇到过（我是两根16组的32）建议去TonyMacX86发个帖问问…问完跟我们讲一声…

What a luxurious problem...Maybe you should ask on TonyMacX86 for the memory issue.

**Comment by oreziam** [comment]
更新BIOS到1.21之后，一直出现ACPI Error AE_NOT_FOUND问题，希望大家悉知
https://github.com/zysuper/Thinkpad-X1-extreme-EFI/issues/19

@Errrneist ，我遇到了以上这个问题，我用了你的EFI后，并升级了BIOS到1.23，还是出现这个错误，这个地方会卡十几分钟甚至半个小时以上才能进系统。

如果我把DSDT.aml文件删掉，则不会卡在这，但是进系统后电量、USB等不可用。

riclava 的方法我不太懂，请问有什么解决办法么？

**Comment by wu-hongjun** [comment]
> 更新BIOS到1.21之后，一直出现ACPI Error AE_NOT_FOUND问题，希望大家悉知
> [zysuper/Thinkpad-X1-extreme-EFI#19](https://github.com/zysuper/Thinkpad-X1-extreme-EFI/issues/19)
> 
> @Errrneist ，我遇到了以上这个问题，我用了你的EFI后，并升级了BIOS到1.23，还是出现这个错误，这个地方会卡十几分钟甚至半个小时以上才能进系统。
> 
> 如果我把DSDT.aml文件删掉，则不会卡在这，但是进系统后电量、USB等不可用。
> 
> riclava 的方法我不太懂，请问有什么解决办法么？

处理器是8850H还是8750H？

**Comment by oreziam** [comment]
我的是8850H 目前是三星32G*1

**Comment by wu-hongjun** [comment]
> 我的是8850H 目前是三星32G*1

那么迷…你大概需要自己patch你自己的dsdt了，目前想不到其他解法

**Comment by oreziam** [comment]
> > 我的是8850H 目前是三星32G*1
> 
> 那么迷…你大概需要自己patch你自己的dsdt了，目前想不到其他解法

我patch了自己的DSDT后解决，但64G内存的引导问题还没解决。
卡在了+++++++++++这个地方。

**Comment by wu-hongjun** [comment]
> > > 我的是8850H 目前是三星32G*1
> > 
> > 
> > 那么迷…你大概需要自己patch你自己的dsdt了，目前想不到其他解法
> 
> 我patch了自己的DSDT后解决，但64G内存的引导问题还没解决。
> 卡在了+++++++++++这个地方。

可以试试看换一个SMBIOS 试试看iMac的 可能是MacbookPro15,2不支持这个内存上限

**Comment by oreziam** [comment]
> > > > 我的是8850H 目前是三星32G*1
> > > 
> > > 
> > > 那么迷…你大概需要自己patch你自己的dsdt了，目前想不到其他解法
> > 
> > 
> > 我patch了自己的DSDT后解决，但64G内存的引导问题还没解决。
> > 卡在了+++++++++++这个地方。
> 
> 可以试试看换一个SMBIOS 试试看iMac的 可能是MacbookPro15,2不支持这个内存上限

我已经自己摸索解决，需要注入内存信息，但要比实际情况多一个卡槽……
也就是我注入的内存信息是4通道5卡槽…… 16G*5
但是系统进入后实际显示是64G
好奇葩的解法。

**Comment by wu-hongjun** [comment]
阔以 我更新了readme.MD，感谢分享～
