### ISSUE TITLE
Drop tables

### ISSUE THREAD

**Issue by Mateo1234454545** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#37]
I see in your beta release you are dropping many tables , like dmar, dbg2 , dbgb etc.

Can you explain that ?

Thank you.

**Comment by wu-hongjun** [comment]
Wait what exactly are you talking about? I did not make such changes (maybe Glover v5033 upgrade made it)

**Comment by wu-hongjun** [comment]
> I see in your beta release you are dropping many tables , like dmar, dbg2 , dbgb etc.
> 
> Can you explain that ?
> 
> Thank you.

If not mentioned in the release notes everything remains the same.

**Comment by Mateo1234454545** [comment]
I don't say that you made any changes. Maybe it was there before , I don't know.

My question is why are you droping these tables ?

**Comment by wu-hongjun** [comment]
> I don't say that you made any changes. Maybe it was there before , I don't know.
> 
> My question is why are you droping these tables ?

zysuper did that I don’t really know either 😂 my config contains some of his early work.
