### ISSUE TITLE
Does Thunderbolt 3 Work?

### ISSUE THREAD

**Issue by oreziam** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#39]
我在使用10.14.5的EFI，插入Thunderbolt 3的移动硬盘（HP P800），无法识别。
插入贝尔金的dock，也无法识别。
插入LG 5K显示器，无法显示。
请问EFI是否没有Thunderbolt 3的驱动？

I am using the EFI of 10.14.5 and I am inserting a Thunderbolt 3 mobile SSD (HP P800)
 that is not work.
Inserting Belkin's dock is also unrecognizable.
Insert LG 5K display, can not be displayed.
Does EFI have no Thunderbolt 3 driver?

**Comment by gfoury** [comment]
I have an [external DisplayPort/DisplayPort/USB/Ethernet adapter](https://www.cablematters.com/pc-989-130-certified-thunderbolt-3-dual-displayport-mini-dock-for-mac-and-windows.aspx). The Ethernet adapter shows up as an AppleIntelI210 (PCIe-connected) and there is a separate XHCI adapter. I have authorized the device using Windows. If I boot up with it attached, the Ethernet and USB work.

Plugging it in after boot does not work.

As far as I know, all external video ports are connected to the 1050, not the iGPU. So unless macOS supports the 1050, DisplayPort outputs should not work.

**Comment by wu-hongjun** [comment]
I do not have a compatible Thunderbolt 3 device so I cannot do anything at this point. So probably not, but please tell me how it goes if you managed to solve it!!

**Comment by oreziam** [comment]
我退掉了淘宝上购买的所有雷电3移动SSD，我放弃了在X1E使用雷电3的想法。
I rejected all TB3 Mobile SSD purchased on Taobao, and I gave up the idea of using TB3 in X1E.

**Comment by wu-hongjun** [comment]
> 我退掉了淘宝上购买的所有雷电3移动SSD，我放弃了在X1E使用雷电3的想法。
> I rejected all TB3 Mobile SSD purchased on Taobao, and I gave up the idea of using TB3 in X1E.

I will buy a Razer Core X to test my RX570 when I get back to states.

**Comment by wu-hongjun** [comment]
> 我退掉了淘宝上购买的所有雷电3移动SSD，我放弃了在X1E使用雷电3的想法。
> I rejected all TB3 Mobile SSD purchased on Taobao, and I gave up the idea of using TB3 in X1E.

我现在用的是一块850Pro走USB3.1 Gen2硬盘盒基本能跑满速
