### ISSUE TITLE
Customized AppleALC layout and problems with VoodooI2C*.kext

### ISSUE THREAD

**Issue by flymin** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#40]
I tried AppleALC with layout 21,11 and your customized version, none of them works on my laptop perfectly. So I made a new layout 31, see [pull #442](https://github.com/acidanthera/AppleALC/pull/442), you can try it out!

v3.0 will cause a 5-min boot lag on my machine. I found out that it is VoodooI2C*.kext which caused the problem as follow:
![ApplePS2MouseDevice problem](https://s2.ax1x.com/2019/08/11/ev0uIx.jpg)
Maybe some acknowledgements could be added for those who use machines but has no I2C devices?

BTW, I make a adjust [release](https://github.com/flymin/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.15.0.3.0.0) for changes I stated above, and your configuration is actually compatible with some 8750 machines (as least mine).

**Comment by wu-hongjun** [comment]
VoodooI2C does nothing on my computer (intended to make touch screen working as someone said in TonyMacX86) so if you think it is problematic just get rid of it. Currently I am traveling and am not actively developing the project, so I will take a look at your release when I have time. Thanks!

**Comment by ergonyc** [comment]
Hey guys,
I spent some time on this...  The problem with VoodooI2C on the X1E is that the trackpad uses an SMCBus.  There are linux drivers that can control the synaptics via i2c through that bus, so in principle its totally possible.  Some folks are working on it, but the VoodooI2C team has it at low priority, so don't hold your breath.
That said the acidanthera versions of VoodooPS2 works great for me. Picks up where Rehabman left off.  I would recommend upgrading to that one.  I prefer gesture support over the track point (which is unsupported).   It also does the basic work for the touch screen.  
In the long term, I'd like to get gestures working on the touchscreen, but will probably require a future version of VoodooI2c and some careful configuration with VoodooPS2 to keep the keyboard 

I'll upload my config, and share some links to the sources I reference when I get a chance.  Everything is working in the latest Mojave release and Catalina beta release... 

Thanks again Errrniest (and Zysuper and all the rest)  for all the work shared here.  Its been a steep learning curve to understand this Hackintosh stuff, but the guides you left made it safe.  ;)

**Comment by wu-hongjun** [comment]
> Hey guys,
> I spent some time on this... The problem with VoodooI2C on the X1E is that the trackpad uses an SMCBus. There are linux drivers that can control the synaptics via i2c through that bus, so in principle its totally possible. Some folks are working on it, but the VoodooI2C team has it at low priority, so don't hold your breath.
> That said the acidanthera versions of VoodooPS2 works great for me. Picks up where Rehabman left off. I would recommend upgrading to that one. I prefer gesture support over the track point (which is unsupported). It also does the basic work for the touch screen.
> In the long term, I'd like to get gestures working on the touchscreen, but will probably require a future version of VoodooI2c and some careful configuration with VoodooPS2 to keep the keyboard
> 
> I'll upload my config, and share some links to the sources I reference when I get a chance. Everything is working in the latest Mojave release and Catalina beta release...
> 
> Thanks again Errrniest (and Zysuper and all the rest) for all the work shared here. Its been a steep learning curve to understand this Hackintosh stuff, but the guides you left made it safe. ;)

Personally I prefer trackpoint over trackpad, I included a version (quite far awhile ago) that prefer trackpad gesture but then found it too hard for me to use (I need the upper three buttons) so I went back to the original. I used to be able to achieve basic touch screen support using the original VoodooPS2Controller but I lost it in 10.15, idk what happened.

**Comment by wdde** [comment]
A few days ago, I found that voodoops2controller.kext with gesture support would cause the screenshot hotkey to fail. I can't use shift-command-3/4/5 to take screenshots. I tried to return to the Rehabman version and found that the screenshot function was back, Then I found that the hotkey command-1/2/3..etc function of the iTerm2 to switch tab window that was bothering me was also worked, but I needed multi-gesture support and had to abandon the screenshot and switch window functions. I don't know if you guys have more support for multi-gestures without affecting the system hotkeys voodoops2controller.kext?

**Comment by wdde** [comment]
the acidanthera versions of VoodooPS2controller.kext is much better, the screenshot hotkey is back

**Comment by flymin** [comment]
> the acidanthera versions of VoodooPS2controller.kext is much better, the screenshot hotkey is back

excellent! I'm using this version and trackpoint, gesture, buttons on trackpad can all be used. Thank you very much!

**Comment by wu-hongjun** [comment]
> > the acidanthera versions of VoodooPS2controller.kext is much better, the screenshot hotkey is back
> 
> excellent! I'm using this version and trackpoint, gesture, buttons on trackpad can all be used. Thank you very much!

Can you please upload the VoodooPS2Controller you are using? Thanks.

**Comment by flymin** [comment]
> > > the acidanthera versions of VoodooPS2controller.kext is much better, the screenshot hotkey is back
> > 
> > 
> > excellent! I'm using this version and trackpoint, gesture, buttons on trackpad can all be used. Thank you very much!
> 
> Can you please upload the VoodooPS2Controller you are using? Thanks.

Just the [latest release version](https://github.com/acidanthera/VoodooPS2/releases/tag/2.0.3), or in my [EFI release](https://github.com/flymin/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.14.6.1.2).

**Comment by wu-hongjun** [comment]
> > > > the acidanthera versions of VoodooPS2controller.kext is much better, the screenshot hotkey is back
> > > 
> > > 
> > > excellent! I'm using this version and trackpoint, gesture, buttons on trackpad can all be used. Thank you very much!
> > 
> > 
> > Can you please upload the VoodooPS2Controller you are using? Thanks.
> 
> Just the [latest release version](https://github.com/acidanthera/VoodooPS2/releases/tag/2.0.3), or in my [EFI release](https://github.com/flymin/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.14.6.1.2).

Cool.

**Comment by wu-hongjun** [comment]
> > > > the acidanthera versions of VoodooPS2controller.kext is much better, the screenshot hotkey is back
> > > 
> > > 
> > > excellent! I'm using this version and trackpoint, gesture, buttons on trackpad can all be used. Thank you very much!
> > 
> > 
> > Can you please upload the VoodooPS2Controller you are using? Thanks.
> 
> Just the [latest release version](https://github.com/acidanthera/VoodooPS2/releases/tag/2.0.3), or in my [EFI release](https://github.com/flymin/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.14.6.1.2).

Much much better. I will draft a new release.
