### ISSUE TITLE
VirtualSMC conflicts...

### ISSUE THREAD

**Issue by ergonyc** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#41]
Heya,  In case you want to try out VirtualSMC again I thought I'd share.  The deeper I have gotten into it, the VirtualSMC / Lilu family of solutions will be much more robust in the long term.  And you have to read fairly deep into the Acidanthera repositories to get the clear instructions about these conflicts. 
-ACPIBatteryManager.kext conflicts with SMCBatteryManager.kext and will cause the boot to hang for about 5 minutes.  With ACPIBatteryManager.kext gone, my boot takes 30 seconds.
You probably also need to use the virtualSMC.efi instead of SMChelper.efi (at least for installation)
I don't think you need the FakePCIID kexts... and I think i have everything working just fine without XHCI-unsupported.  

Here's what I'm using: https://github.com/ergonyc/BlackMac-ThinkPad-X1E

**Comment by wu-hongjun** [comment]
I am currently traveling and will get back to you when I have time. VirtualSMC caused many issues (overheating, boot lag, but most importantly, wifi would not load until 3-5 minutes later, which I cannot live with). While VSMC is more robust in the long run, having an everything working version for the upcoming 10.15 is my comfort zone and I am currently pretty happy with it. Everything works except the battery leak issue for roughly 5%/hr which we have not solve, but does not impact day to day use.

**Comment by wu-hongjun** [comment]
> Heya, In case you want to try out VirtualSMC again I thought I'd share. The deeper I have gotten into it, the VirtualSMC / Lilu family of solutions will be much more robust in the long term. And you have to read fairly deep into the Acidanthera repositories to get the clear instructions about these conflicts.
> -ACPIBatteryManager.kext conflicts with SMCBatteryManager.kext and will cause the boot to hang for about 5 minutes. With ACPIBatteryManager.kext gone, my boot takes 30 seconds.
> You probably also need to use the virtualSMC.efi instead of SMChelper.efi (at least for installation)
> I don't think you need the FakePCIID kexts... and I think i have everything working just fine without XHCI-unsupported.
> 
> Here's what I'm using: https://github.com/ergonyc/BlackMac-ThinkPad-X1E

Oh btw which CPU are you using?

**Comment by ergonyc** [comment]
I'm using the i7-8850H

**Comment by anht3889** [comment]
@Errrneist I just notice that the latest VirtualSMC is working perfectly on Catalina. The time for boot is less than 10 secs. It seems like this is the time we should move from FakeSMC to VirtualSMC.
