### ISSUE TITLE
2CS or CS2

### ISSUE THREAD

**Issue by Invisiblebanana789** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#42]
Hey there, 

The Windows Drivers section mentions a CS2 driver, but then links to a 2CS driver page. 
"Windows drivers for Wifi Adapters:
Windows Driver for BRCM94360CS2: If you try to use an BCM94360CS2/BCM94360CD Card To NGFF(M.2)Key A/E Adapter For macOS to install the native card used on Macbook Pro."

Later in Post-Install, it states to not buy the CS2.

I ordered a 2CS w/ wdxxfu adapter, and it seems like @Errrneist is using a 2CS too, just wanted to confirm that the 2CS is the correct wifi card and also clear up a few typos.

Thanks!

**Comment by wu-hongjun** [comment]
2CS, not CS2.

**Comment by Invisiblebanana789** [comment]
Alright, thanks!

**Comment by wu-hongjun** [comment]
Good catch, I think I corrected the typo.
