### ISSUE TITLE
Random BT Adapter Questions

### ISSUE THREAD

**Issue by Invisiblebanana789** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#44]
Hey there,

Quick questions about the Wdxxfu BT Adapter:

1) Do you think it would work with the Gen 2 Extreme? Any percent chance estimate?
2) Assuming that using the CS2 on the Gen 2 will not make MacOS and Windows freeze, would the adapter for BT work with the CS2?

Link to Gen 2 Internals: https://imgur.com/gallery/u93b4jw

Thanks!

-IB

**Comment by wu-hongjun** [comment]
1: Yes
2: Yes

We are using the Smartcard USB2.0 bus, so I can't think of a problem why it won't work.

**Comment by Invisiblebanana789** [comment]
cool thx
