### ISSUE TITLE
使用温度控制风扇启停及转速

### ISSUE THREAD

**Issue by wdde** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#45]
测了两周，没什么问题，可以设置开启温度，关闭温度，设置几个温度阈值关联风扇速度。
两个步骤，首先给dsdt打补丁，再手动修改ssdt-cfan里的温度速度值，另存aml，放到patched目录，重启，除了关机有个acpi报错（不稀奇，X86服务器+RHEL也有此类报错），其他都没问题。
具体参考一个github: thinkpad-p51-hackintosh，dsdt打补丁，使用maciasl，打开repo里的dsdt utility文件，apply到dsdt上即可

**Comment by wu-hongjun** [comment]
(其实我觉得我的风扇还ok啊一般到65才开始转。。。

**Comment by wdde** [comment]
65太烫了，键盘打字多感觉不舒服

**Comment by wu-hongjun** [comment]
> 65太烫了，键盘打字多感觉不舒服

这几天给X1E换了硅脂 用的是Kyonaut 温度暴降五六度现在待机一般稳定在57左右 强的一批

**Comment by wdde** [comment]
这么强啊？我之前用的金属硅脂也就降几度， 可惜很多东西到了天朝价格离谱

**Comment by wu-hongjun** [comment]
> 这么强啊？我之前用的金属硅脂也就降几度， 可惜很多东西到了天朝价格离谱

我的用了一年硅脂都硬了 随便换个什么都可以 不一定要这个牌子

**Comment by flymin** [comment]
> 测了两周，没什么问题，可以设置开启温度，关闭温度，设置几个温度阈值关联风扇速度。
> 两个步骤，首先给dsdt打补丁，再手动修改ssdt-cfan里的温度速度值，另存aml，放到patched目录，重启，除了关机有个acpi报错（不稀奇，X86服务器+RHEL也有此类报错），其他都没问题。
> 具体参考一个github: thinkpad-p51-hackintosh，dsdt打补丁，使用maciasl，打开repo里的dsdt utility文件，apply到dsdt上即可

能不能问一下具体是修改哪几行代码？是只修改[43-49](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/blob/8ce85dac09fd585281f110b034d4ce55f0055b59/EFI/CLOVER/ACPI/patched/SSDT-CFAN.dsl#L43)就行吗？我把数值调成40 45 55 75，也没感觉出什么变化呀，闲置状态依旧是55-60度...

**Comment by wdde** [comment]
> > 测了两周，没什么问题，可以设置开启温度，关闭温度，设置几个温度阈值关联风扇速度。
> > 两个步骤，首先给dsdt打补丁，再手动修改ssdt-cfan里的温度速度值，另存aml，放到patched目录，重启，除了关机有个acpi报错（不稀奇，X86服务器+RHEL也有此类报错），其他都没问题。
> > 具体参考一个github: thinkpad-p51-hackintosh，dsdt打补丁，使用maciasl，打开repo里的dsdt utility文件，apply到dsdt上即可
> 
> 能不能问一下具体是修改哪几行代码？是只修改[43-49](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/blob/8ce85dac09fd585281f110b034d4ce55f0055b59/EFI/CLOVER/ACPI/patched/SSDT-CFAN.dsl#L43)就行吗？我把数值调成40 45 55 75，也没感觉出什么变化呀，闲置状态依旧是55-60度...

我的ssdt-cfan，超过48度开启风扇，速度级别1（最慢），温度到43度，风扇停止。
    Name (FTAB, Buffer()
    {
        43, 0,
        48, 1,
        60, 3,
        80, 7,
    })

记住，需要把ssdt-cfan保存为aml格式，aml格式的文件不再是十进制的温度设置，而会转换为16进制；对你的dsdt打补丁（DSDT_utilities_patch.txt），否则风扇控制不会生效。

**Comment by flymin** [comment]
> > > 测了两周，没什么问题，可以设置开启温度，关闭温度，设置几个温度阈值关联风扇速度。
> > > 两个步骤，首先给dsdt打补丁，再手动修改ssdt-cfan里的温度速度值，另存aml，放到patched目录，重启，除了关机有个acpi报错（不稀奇，X86服务器+RHEL也有此类报错），其他都没问题。
> > > 具体参考一个github: thinkpad-p51-hackintosh，dsdt打补丁，使用maciasl，打开repo里的dsdt utility文件，apply到dsdt上即可
> > 
> > 
> > 能不能问一下具体是修改哪几行代码？是只修改[43-49](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/blob/8ce85dac09fd585281f110b034d4ce55f0055b59/EFI/CLOVER/ACPI/patched/SSDT-CFAN.dsl#L43)就行吗？我把数值调成40 45 55 75，也没感觉出什么变化呀，闲置状态依旧是55-60度...
> 
> 我的ssdt-cfan，超过48度开启风扇，速度级别1（最慢），温度到43度，风扇停止。
> Name (FTAB, Buffer()
> {
> 43, 0,
> 48, 1,
> 60, 3,
> 80, 7,
> })
> 
> 记住，需要把ssdt-cfan保存为aml格式，aml格式的文件不再是十进制的温度设置，而会转换为16进制；对你的dsdt打补丁（DSDT_utilities_patch.txt），否则风扇控制不会生效。

难道是[#48](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/48#issue-504370364)这位老哥提到的10.15的问题？我改成你这样的参数设置也没感觉出来任何变化...你是在10.15吗？

**Comment by wdde** [comment]
10.14.6,
Also confirm that ACPIPoller.kext exists in the kext/other directory

**Comment by flymin** [comment]
> 10.14.6,
> Also confirm that ACPIPoller.kext exists in the kext/other directory

添加之后有效了，非常感谢！

**Comment by eunrui** [comment]
> > > 测了两周，没什么问题，可以设置开启温度，关闭温度，设置几个温度阈值关联风扇速度。
> > > 两个步骤，首先给dsdt打补丁，再手动修改ssdt-cfan里的温度速度值，另存aml，放到patched目录，重启，除了关机有个acpi报错（不稀奇，X86服务器+RHEL也有此类报错），其他都没问题。
> > > 具体参考一个github: thinkpad-p51-hackintosh，dsdt打补丁，使用maciasl，打开repo里的dsdt utility文件，apply到dsdt上即可
> > 
> > 
> > 能不能问一下具体是修改哪几行代码？是只修改[43-49](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/blob/8ce85dac09fd585281f110b034d4ce55f0055b59/EFI/CLOVER/ACPI/patched/SSDT-CFAN.dsl#L43)就行吗？我把数值调成40 45 55 75，也没感觉出什么变化呀，闲置状态依旧是55-60度...
> 
> 我的ssdt-cfan，超过48度开启风扇，速度级别1（最慢），温度到43度，风扇停止。
> Name (FTAB, Buffer()
> {
> 43, 0,
> 48, 1,
> 60, 3,
> 80, 7,
> })
> 
> 记住，需要把ssdt-cfan保存为aml格式，aml格式的文件不再是十进制的温度设置，而会转换为16进制；对你的dsdt打补丁（DSDT_utilities_patch.txt），否则风扇控制不会生效。

opencore该怎么用呢 已经不使用DSDT了
