### ISSUE TITLE
SD Card Reader gone after sleep

### ISSUE THREAD

**Issue by Romsky** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#46]
As title says... Cardreader is working perfect until I wake X1 from sleep... Cardreader is then non functional. (No SD-Card will detected)

**Comment by wu-hongjun** [comment]
Which version are you using? I am not having this issue on my end,

**Comment by Romsky** [comment]
Iam using 10.14.6. with Bios from Juli 2019. All is working but Cardreader is gone after wake.

**Comment by wu-hongjun** [comment]
> Iam using 10.14.6. with Bios from Juli 2019. All is working but Cardreader is gone after wake.

10.14.6 is a thing from the past and we moved to 10.15 since the first beta, we are currently on 10.15.0 PB8. You can try the latest release v10.15.0.3.3 but there is no way I can help you to solve issue in Mojave...

**Comment by Romsky** [comment]
Hmm, ok... I use device for production so beta is a no go. And even with release state, I have no advantage in using 10.5. If I read right there are more Problems in Catalina (Battery etc.) than in Mojave. But thanks for your Info... I will try to find a solution.

Greets

**Comment by wu-hongjun** [comment]
> Hmm, ok... I use device for production so beta is a no go. And even with release state, I have no advantage in using 10.5. If I read right there are more Problems in Catalina (Battery etc.) than in Mojave. But thanks for your Info... I will try to find a solution.
> 
> Greets

However v10.15.0.3.3 should be downward compatible. So go grab a rescue USB and give it a try. I think this might solve your issue. Every new release fixes something.

**Comment by wdde** [comment]
My Hackintosh (20MF000CUS) is on 10.14.6. I just tested it and the reader works fine (although the system report says "This computer does not contain any Apple internal memory card readers."), I'm not sure but I suggest you check the uia_exclude in the boot parameter. My current configuration is uia_exclude=HS14, HS13, HS12, HS11, HS05, HS06, USR1, USR2,

**Comment by wu-hongjun** [comment]
> My Hackintosh (20MF000CUS) is on 10.14.6. I just tested it and the reader works fine (although the system report says "This computer does not contain any Apple internal memory card readers."), I'm not sure but I suggest you check the uia_exclude in the boot parameter. My current configuration is uia_exclude=HS14, HS13, HS12, HS11, HS05, HS06, USR1, USR2,

Since you don't have an actual computer that is fine (Because the internal SD reader is connected via the USB bus), you should see the device under /System Info/USB/. If it works, it works.
