### ISSUE TITLE
我首先在10.15上使用了本EFI(3.3)似乎很多设置都无效了

### ISSUE THREAD

**Issue by BrettCao** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#48]
风扇控制，触控手势等似乎都无效了

**Comment by wu-hongjun** [comment]
你有没有patch你自己的dsdt？

**Comment by BrettCao** [comment]
我没有，我完全使用的你发布的efi

**Comment by wu-hongjun** [comment]
那就对了 纯用别人的EFI是行不通的哟

**Comment by wu-hongjun** [comment]
> 我没有，我完全使用的你发布的efi

运气好的话就能用 运气不好的话就只能从零开始Patch DSDT啦

**Comment by BrettCao** [comment]
您是8850h+1050的配置吗

**Comment by BrettCao** [comment]
小白一个,有没有教程啊 😭

**Comment by BrettCao** [comment]
哦，对了
我使用的是10.15正式版

**Comment by wu-hongjun** [comment]
> 哦，对了
> 我使用的是10.15正式版

教程嘛自己去TonyMacX86看教程呀 我也是8850H+1050TiMQ可能是你脸比较黑

**Comment by BrettCao** [comment]
请问一下触摸板的dsdt是那个文件

**Comment by BrettCao** [comment]
我现在不能正常使用手势，想先解决一下

**Comment by wu-hongjun** [comment]
> 请问一下触摸板的dsdt是那个文件

DSDT 就是DSDT.aml, 触摸板是VoodooPSController和Voodooi2C/i2CHID的kext

**Comment by wdde** [comment]
看readme，后面有其他人共享的hackintosh 项目，找8850的，试试看

**Comment by BrettCao** [comment]
好像只有这位老哥实现了多点触控和手势

**Comment by wu-hongjun** [comment]
> 好像只有这位老哥实现了多点触控和手势

除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了

**Comment by BrettCao** [comment]
老哥忙完帮看一眼吧，我也几乎完美了，就是触控屏和手势不能用，惨惨惨

**Comment by BrettCao** [comment]
话说你升级了10.15正式版了吗

> > 好像只有这位老哥实现了多点触控和手势
> 
> 除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了

**Comment by wu-hongjun** [comment]
> 话说你升级了10.15正式版了吗
> 
> > > 好像只有这位老哥实现了多点触控和手势
> > 
> > 
> > 除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了

我好像是PB10还是啥我忘了 最近因为在做ML需要用N卡有一段时间没动mac了我也没怎么管了😅因为3.3其实就是小改过的3.2 which我上个月十号以后就基本没动过了

**Comment by BrettCao** [comment]
> > 话说你升级了10.15正式版了吗
> > > > 好像只有这位老哥实现了多点触控和手势
> > > 
> > > 
> > > 除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了
> 
> 我好像是PB10还是啥我忘了 最近因为在做ML需要用N卡有一段时间没动mac了我也没怎么管了😅因为3.3其实就是小改过的3.2 which我上个月十号以后就基本没动过了

总感觉是我升级了正式版的原因，正式版和测试版的不同还是很明显的

**Comment by wu-hongjun** [comment]
> > > 话说你升级了10.15正式版了吗
> > > > > 好像只有这位老哥实现了多点触控和手势
> > > > 
> > > > 
> > > > 除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了
> > 
> > 
> > 我好像是PB10还是啥我忘了 最近因为在做ML需要用N卡有一段时间没动mac了我也没怎么管了😅因为3.3其实就是小改过的3.2 which我上个月十号以后就基本没动过了
> 
> 总感觉是我升级了正式版的原因，正式版和测试版的不同还是很明显的

可怕 那就不升正式版了

**Comment by wu-hongjun** [comment]
> > > > 话说你升级了10.15正式版了吗
> > > > > > 好像只有这位老哥实现了多点触控和手势
> > > > > 
> > > > > 
> > > > > 除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了
> > > 
> > > 
> > > 我好像是PB10还是啥我忘了 最近因为在做ML需要用N卡有一段时间没动mac了我也没怎么管了😅因为3.3其实就是小改过的3.2 which我上个月十号以后就基本没动过了
> > 
> > 
> > 总感觉是我升级了正式版的原因，正式版和测试版的不同还是很明显的
> 
> 可怕 那就不升正式版了

现在是Beta 19A582a

**Comment by BrettCao** [comment]
> > > > > 话说你升级了10.15正式版了吗
> > > > > > > 好像只有这位老哥实现了多点触控和手势
> > > > > > 
> > > > > > 
> > > > > > 除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了
> > > > 
> > > > 
> > > > 我好像是PB10还是啥我忘了 最近因为在做ML需要用N卡有一段时间没动mac了我也没怎么管了😅因为3.3其实就是小改过的3.2 which我上个月十号以后就基本没动过了
> > > 
> > > 
> > > 总感觉是我升级了正式版的原因，正式版和测试版的不同还是很明显的
> > 
> > 
> > 可怕 那就不升正式版了
> 
> 现在是Beta 19A582a

升一下吧，你可以的，调试后把efi发出来额 🥇

**Comment by wu-hongjun** [comment]
> > > > > > 话说你升级了10.15正式版了吗
> > > > > > > > 好像只有这位老哥实现了多点触控和手势
> > > > > > > 
> > > > > > > 
> > > > > > > 除了zysuper他们都是参考我的🤣不过我最近忙科研实在抽不出时间看这个repo...因为我的本子已经完美了
> > > > > 
> > > > > 
> > > > > 我好像是PB10还是啥我忘了 最近因为在做ML需要用N卡有一段时间没动mac了我也没怎么管了😅因为3.3其实就是小改过的3.2 which我上个月十号以后就基本没动过了
> > > > 
> > > > 
> > > > 总感觉是我升级了正式版的原因，正式版和测试版的不同还是很明显的
> > > 
> > > 
> > > 可怕 那就不升正式版了
> > 
> > 
> > 现在是Beta 19A582a
> 
> 升一下吧，你可以的，调试后把efi发出来额 🥇

打扰了

**Comment by darkal** [comment]
升级了正式版，没发现和beta版有什么差别。。

**Comment by BrettCao** [comment]
> 升级了正式版，没发现和beta版有什么差别。。

那就是我真的脸黑了

**Comment by BrettCao** [comment]
你格式化的时候选的是区分大小写的格式，还是不区分的

**Comment by wu-hongjun** [comment]
> 你格式化的时候选的是区分大小写的格式，还是不区分的
Journaled 好像是不区分的

**Comment by BrettCao** [comment]
> > 你格式化的时候选的是区分大小写的格式，还是不区分的
> > Journaled 好像是不区分的

刚刚试了一下，用你的efi，在第一阶段安装时候是可以触控的，进入配置的时候，就不支持了，是不是我的分区有问题，帮我看一下好吗？HD0是苹果 HD1 是win
![TIM截图20191013083917](https://user-images.githubusercontent.com/17780089/66713037-0db20480-edd8-11e9-8e2d-970456e93af5.png)

**Comment by BrettCao** [comment]
![TIM截图20191013090137](https://user-images.githubusercontent.com/17780089/66713273-266fe980-eddb-11e9-8230-8727e8e546b1.png)
详细目录

**Comment by wu-hongjun** [comment]
> > > 你格式化的时候选的是区分大小写的格式，还是不区分的
> > > Journaled 好像是不区分的
> 
> 刚刚试了一下，用你的efi，在第一阶段安装时候是可以触控的，进入配置的时候，就不支持了，是不是我的分区有问题，帮我看一下好吗？HD0是苹果 HD1 是win
> ![TIM截图20191013083917](https://user-images.githubusercontent.com/17780089/66713037-0db20480-edd8-11e9-8e2d-970456e93af5.png)

不清楚 我们难道不是用苹果自带的Disk Utilities分的区嘛 用Disk Utilities分出来都是一样的

**Comment by BrettCao** [comment]
我觉得我的EFI没弄对，我只是把一个磁盘给转换成了atfs，其他的还是ntfs

**Comment by eunrui** [comment]
> 我觉得我的EFI没弄对，我只是把一个磁盘给转换成了atfs，其他的还是ntfs

目前我发现的是 启动参数-v才能开启触控 去掉-v就不行 奇奇怪怪~..

**Comment by wu-hongjun** [comment]
> > 我觉得我的EFI没弄对，我只是把一个磁盘给转换成了atfs，其他的还是ntfs
> 
> 目前我发现的是 启动参数-v才能开启触控 去掉-v就不行 奇奇怪怪~..

我之前更奇怪 必须要-v才能进系统 不然就自动重启

**Comment by eunrui** [comment]
> > > 我觉得我的EFI没弄对，我只是把一个磁盘给转换成了atfs，其他的还是ntfs
> > 
> > 
> > 目前我发现的是 启动参数-v才能开启触控 去掉-v就不行 奇奇怪怪~..
> 
> 我之前更奇怪 必须要-v才能进系统 不然就自动重启

前几个版本换VirtualSMC的时候是这样，最近我试了下最新的版本可以用了hhhhhha.
之前用1080P的时候您的EFI总是死机又没错误报告，后来搬用flymin的EFI就没事了，最近换了4k屏用您的还是死机卡住不动，对比了一下flymin方案他打了缓冲帧补丁改了2048显存，我也改了一下，但是开机会卡在-v或者空读条，爬了一下墙发现4k的不能开启DVMT 32MB预分配这个，flymin的1080P开启了这个，现在解决了可以开心的使用了！~(您的列表里列出的其他人EFI方案也有说冻屏的现象，或许这可以帮到他们)
![image](https://user-images.githubusercontent.com/49180440/81047823-cd3de380-8eed-11ea-9c2d-61b133dc2f36.png)

**Comment by wu-hongjun** [comment]
> > > > 我觉得我的EFI没弄对，我只是把一个磁盘给转换成了atfs，其他的还是ntfs
> > > 
> > > 
> > > 目前我发现的是 启动参数-v才能开启触控 去掉-v就不行 奇奇怪怪~..
> > 
> > 
> > 我之前更奇怪 必须要-v才能进系统 不然就自动重启
> 
> 前几个版本换VirtualSMC的时候是这样，最近我试了下最新的版本可以用了hhhhhha.
> 之前用1080P的时候您的EFI总是死机又没错误报告，后来搬用flymin的EFI就没事了，最近换了4k屏用您的还是死机卡住不动，对比了一下flymin方案他打了缓冲帧补丁改了2048显存，我也改了一下，但是开机会卡在-v或者空读条，爬了一下墙发现4k的不能开启DVMT 32MB预分配这个，flymin的1080P开启了这个，现在解决了可以开心的使用了！~(您的列表里列出的其他人EFI方案也有说冻屏的现象，或许这可以帮到他们)
> ![image](https://user-images.githubusercontent.com/49180440/81047823-cd3de380-8eed-11ea-9c2d-61b133dc2f36.png)

不清楚 这台本子我出掉了 换了台雷蛇...

**Comment by eunrui** [comment]
> > > > > 我觉得我的EFI没弄对，我只是把一个磁盘给转换成了atfs，其他的还是ntfs
> > > > 
> > > > 
> > > > 目前我发现的是 启动参数-v才能开启触控 去掉-v就不行 奇奇怪怪~..
> > > 
> > > 
> > > 我之前更奇怪 必须要-v才能进系统 不然就自动重启
> > 
> > 
> > 前几个版本换VirtualSMC的时候是这样，最近我试了下最新的版本可以用了hhhhhha.
> > 之前用1080P的时候您的EFI总是死机又没错误报告，后来搬用flymin的EFI就没事了，最近换了4k屏用您的还是死机卡住不动，对比了一下flymin方案他打了缓冲帧补丁改了2048显存，我也改了一下，但是开机会卡在-v或者空读条，爬了一下墙发现4k的不能开启DVMT 32MB预分配这个，flymin的1080P开启了这个，现在解决了可以开心的使用了！~(您的列表里列出的其他人EFI方案也有说冻屏的现象，或许这可以帮到他们)
> > ![image](https://user-images.githubusercontent.com/49180440/81047823-cd3de380-8eed-11ea-9c2d-61b133dc2f36.png)
> 
> 不清楚 这台本子我出掉了 换了台雷蛇...

哦吼，依然感谢您为该机型做出的贡献。
