### ISSUE TITLE
Trackpad not working with Clover-booted Windows

### ISSUE THREAD

**Issue by alexschomb** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#5]
I noticed that the trackpad is not working in Windows if booted from your Clover configuration. It does work if booted by the regular Windows Boot Manager. For macOS it does work, although it seems to be buggy/jumping (so does the Thinkpad pointing stick).

**Comment by darkal** [comment]
I have the same problem.

**Comment by wu-hongjun** [comment]
The trackpoint appears to be pointy, and that is true...I also experienced this problem on my old P50. Windows booted by clover appears to be buggy in general. One temporary workaround for me is to make the boot time in clover -1 so it goes right into the macOS and press F12 each time when I want to switch OS during restart.

**Comment by wu-hongjun** [comment]
Up until now, so far not much can be done for this issue. My recommendation is just use F12 and set clover boot time to 2sec or -1sec(if you don't want to see OS selection at all, but might be harder later when your laptop has something wrong). Everything else should work fine.
