### ISSUE TITLE
Can eGPU work properly if iGPU is not disabled?

### ISSUE THREAD

**Issue by darkal** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#51]
There is no TB3 gpu dock available on hand. -。-   
Can eGPU be recognized and used without disabling iGPU?

手头上没有可用的雷电显卡坞，在不禁用iGPU的情况下，eGPU能否正常识别并使用？

**Comment by wu-hongjun** [comment]
Mine cannot.  You can try try see :)

**Comment by wu-hongjun** [comment]
> There is no TB3 gpu dock available on hand. -。-
> Can eGPU be recognized and used without disabling iGPU?
> 
> 手头上没有可用的雷电显卡坞，在不禁用iGPU的情况下，eGPU能否正常识别并使用？

1050tiMQ真的其实还是功耗不错的我觉得 你没有扩展显卡老老实实用igpu就ok啊

**Comment by darkal** [comment]
displaylink 接4K显示器开retina 1080p模式性能还是不行，想买个eGPU放家里外接屏幕，平时不外接的话还是用iGPU，哈哈。。

**Comment by wu-hongjun** [comment]
> displaylink 接4K显示器开retina 1080p模式性能还是不行，想买个eGPU放家里外接屏幕，平时不外接的话还是用iGPU，哈哈。。

你知道BIOS切GPU有多方便吗...快得很
