### ISSUE TITLE
windows 没有声音

### ISSUE THREAD

**Issue by xiahanting** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#52]
英语不好，用中文描述。

  我是windows10 ，manjaro ，Mac 10.15 三系统。

 用v3.3 ，3.4版本，通过clover 引导选择界面进入 windows10 时，windows 10会没有声音。
 但是，通过clover 引导选择界面，进入linux 发行版 manjaro时，声音正常。

尝试修改了layid，但是没有效果。

请帮忙，谢谢.

**Comment by wu-hongjun** [comment]
我不是在Readme不是说了不要用Clover引导Windows吗😂用F12

**Comment by xiahanting** [comment]
好的，谢谢。
3.4很完美，现在只剩下一个睡眠耗电问题。

**Comment by wu-hongjun** [comment]
> 好的，谢谢。
> 3.4很完美，现在只剩下一个睡眠耗电问题。

小问题 但是好麻烦 不影响使用 懒得搞了

**Comment by darkal** [comment]
> 好的，谢谢。
> 3.4很完美，现在只剩下一个睡眠耗电问题。

睡眠耗电自行提取并patch dsdt就好了
