### ISSUE TITLE
请问现在雷电3可以识别了吗？

### ISSUE THREAD

**Issue by andyy24** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#53]
很久没来了，不知道有没有进展？

**Comment by wu-hongjun** [comment]
解决了 具体看readme.MD

**Comment by andyy24** [comment]
我加入了SSDT-TB3.aml，但是依然显示驱动程序未载入，请问还有其他地方要修改吗？

**Comment by andyy24** [comment]
> 解决了 具体看readme.MD

我加入了SSDT-TB3.aml，但是依然显示驱动程序未载入，请问还有其他地方要修改吗？

**Comment by wu-hongjun** [comment]
> > 解决了 具体看readme.MD
> 
> 我加入了SSDT-TB3.aml，但是依然显示驱动程序未载入，请问还有其他地方要修改吗？

那个aml不关键 系统信息一直都会显示没有加载驱动的 问题不大

**Comment by andyy24** [comment]
> > > 解决了 具体看readme.MD
> > 
> > 
> > 我加入了SSDT-TB3.aml，但是依然显示驱动程序未载入，请问还有其他地方要修改吗？
> 
> 那个aml不关键 系统信息一直都会显示没有加载驱动的 问题不大

也就是说在clover界面插入tb3设备进入系统就自动识别了？

**Comment by andyy24** [comment]
另外推荐一个帖子 http://bbs.pcbeta.com/viewthread-1827871-1-1.html 按这个帖子修改可以增加长按电源键，跳出关机选项。
![Snipaste_2019-11-08_16-40-42](https://user-images.githubusercontent.com/22165433/68462009-904aaa00-0246-11ea-8a04-0f6de6cc2100.png)

**Comment by wu-hongjun** [comment]
> > > > 解决了 具体看readme.MD
> > > 
> > > 
> > > 我加入了SSDT-TB3.aml，但是依然显示驱动程序未载入，请问还有其他地方要修改吗？
> > 
> > 
> > 那个aml不关键 系统信息一直都会显示没有加载驱动的 问题不大
> 
> 也就是说在clover界面插入tb3设备进入系统就自动识别了？

我感觉得开机前就插上
