### ISSUE TITLE
Quick question for Errrneist

### ISSUE THREAD

**Issue by Invisiblebanana789** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#54]
Hey there, 

Is your X1E1 a 20MF000DUS (8850H, 32GB, UHD, 1TB) or was it custom-configured?

Thanks!

**Comment by wu-hongjun** [comment]
![C0C1E362-3CB5-4629-8D38-130C2B07208E](https://user-images.githubusercontent.com/27667864/68503993-f587a680-0218-11ea-82bc-8198be2f4da8.jpeg)
I don’t remember I configured it so it should be default 20MF.
