### ISSUE TITLE
特地来感谢一下

### ISSUE THREAD

**Issue by BrettCao** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#55]
新版本几乎解决了我的所有问题，只有声音还无法使用

**Comment by wu-hongjun** [comment]
那就读一读ReadMe.MD的AppleALC部分就解决了

**Comment by BrettCao** [comment]
> 那就读一读ReadMe.MD的AppleALC部分就解决了

是的，我更新了最新版的alc，已经可以正常运行

**Comment by darkal** [comment]
@Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香

**Comment by wu-hongjun** [comment]
> @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香

我看了一下 吹爆 双十一直接买了

**Comment by darkal** [comment]
> > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> 
> 我看了一下 吹爆 双十一直接买了

嗯，和X1E比起来屏幕怎么样

**Comment by wu-hongjun** [comment]
> @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香

X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9

**Comment by wu-hongjun** [comment]
> > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > 
> > 
> > 我看了一下 吹爆 双十一直接买了
> 
> 嗯，和X1E比起来屏幕怎么样

没回国呢 还没拿到

**Comment by darkal** [comment]
> > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> 
> X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9

个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...

**Comment by wu-hongjun** [comment]
> > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > 
> > 
> > 我看了一下 吹爆 双十一直接买了
> 
> 嗯，和X1E比起来屏幕怎么样



> > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > 
> > 
> > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> 
> 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...

贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧 
Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh

**Comment by darkal** [comment]
> > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > 
> > > 
> > > 我看了一下 吹爆 双十一直接买了
> > 
> > 
> > 嗯，和X1E比起来屏幕怎么样
> 
> > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > 
> > > 
> > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > 
> > 
> > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> 
> 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh

老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，😂

**Comment by wu-hongjun** [comment]
> > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > 
> > > > 
> > > > 我看了一下 吹爆 双十一直接买了
> > > 
> > > 
> > > 嗯，和X1E比起来屏幕怎么样
> > 
> > 
> > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > 
> > > > 
> > > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > > 
> > > 
> > > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > 
> > 
> > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> 
> 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，![😂](chrome-extension://cahedbegdkagmcjfolhdlechbkeaieki/images/apple/1f602.png)

那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果

**Comment by darkal** [comment]
> @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> 
> 我看了一下 吹爆 双十一直接买了
> 
> 嗯，和X1E比起来屏幕怎么样
> 
> @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> 
> X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> 
> 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> 
> 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> 
> 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> 
> 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果

我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈

**Comment by wu-hongjun** [comment]
> > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > 我看了一下 吹爆 双十一直接买了
> > 嗯，和X1E比起来屏幕怎么样
> > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> > 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> > 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果
> 
> 我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈

巧了 你编程什么方向啊

**Comment by darkal** [comment]
> > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > 我看了一下 吹爆 双十一直接买了
> > > 嗯，和X1E比起来屏幕怎么样
> > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> > > 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> > > 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果
> > 
> > 
> > 我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈
> 
> 巧了 你编程什么方向啊

以前做android app，现在做大数据（hadoop全家桶）和数据挖掘

**Comment by wu-hongjun** [comment]
> > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > 我看了一下 吹爆 双十一直接买了
> > > > 嗯，和X1E比起来屏幕怎么样
> > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > > > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > > > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > > > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > > > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> > > > 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> > > > 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果
> > > 
> > > 
> > > 我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈
> > 
> > 
> > 巧了 你编程什么方向啊
> 
> 以前做android app，现在做大数据（hadoop全家桶）和数据挖掘

可以 我在搞深度学习 找不到工作就去找你哈哈哈

**Comment by darkal** [comment]
> > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > 我看了一下 吹爆 双十一直接买了
> > > > > 嗯，和X1E比起来屏幕怎么样
> > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > > > > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > > > > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > > > > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > > > > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> > > > > 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> > > > > 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果
> > > > 
> > > > 
> > > > 我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈
> > > 
> > > 
> > > 巧了 你编程什么方向啊
> > 
> > 
> > 以前做android app，现在做大数据（hadoop全家桶）和数据挖掘
> 
> 可以 我在搞深度学习 找不到工作就去找你哈哈哈

哈哈，我们主要是电商领域，个性化推荐，能上深度就更好啦

**Comment by wu-hongjun** [comment]
> > > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > > 我看了一下 吹爆 双十一直接买了
> > > > > > 嗯，和X1E比起来屏幕怎么样
> > > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > > > > > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > > > > > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > > > > > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > > > > > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> > > > > > 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> > > > > > 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果
> > > > > 
> > > > > 
> > > > > 我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈
> > > > 
> > > > 
> > > > 巧了 你编程什么方向啊
> > > 
> > > 
> > > 以前做android app，现在做大数据（hadoop全家桶）和数据挖掘
> > 
> > 
> > 可以 我在搞深度学习 找不到工作就去找你哈哈哈
> 
> 哈哈，我们主要是电商领域，个性化推荐，能上深度就更好啦

没事 我毕业还有个两年哈哈哈

**Comment by darkal** [comment]
> > > > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > > > 我看了一下 吹爆 双十一直接买了
> > > > > > > 嗯，和X1E比起来屏幕怎么样
> > > > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > > > > > > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > > > > > > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > > > > > > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > > > > > > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> > > > > > > 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> > > > > > > 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果
> > > > > > 
> > > > > > 
> > > > > > 我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈
> > > > > 
> > > > > 
> > > > > 巧了 你编程什么方向啊
> > > > 
> > > > 
> > > > 以前做android app，现在做大数据（hadoop全家桶）和数据挖掘
> > > 
> > > 
> > > 可以 我在搞深度学习 找不到工作就去找你哈哈哈
> > 
> > 
> > 哈哈，我们主要是电商领域，个性化推荐，能上深度就更好啦
> 
> 没事 我毕业还有个两年哈哈哈

少年未来可期啊，加油2333

**Comment by wu-hongjun** [comment]
> > > > > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > > > > 我看了一下 吹爆 双十一直接买了
> > > > > > > > 嗯，和X1E比起来屏幕怎么样
> > > > > > > > @Errrneist 感谢大佬对X1E的付出，话说Y9000X没独显，应该可以直接扩展屏幕，真香
> > > > > > > > X1E不屏蔽集显根本eGPU没法用 屏蔽了集显macOS又必须把2080Ti拆了换RX570的eGPU才能用 各种bug CPU也疯狂降频 Y9000X目测香的一批而且M.2有USB通道不需要折腾蓝牙 还能上i9
> > > > > > > > 个人觉得Y9000X除了有小键盘不适应，别的看起来都很好啊，最近X1E的电池也不行了，打算直接上16寸的白果了...
> > > > > > > > 贵啊 rmbp16也太贵了美版乞丐版加个税比得上顶配i9的Y900X了国行应该更贵吧
> > > > > > > > Y9000X性价比巨高i9+32G+2T而且rmbp16那散热……单热管压i9+RX5500我觉得不太行
> > > > > > > > 显卡嘛外接显卡挺香的其实真的没啥必要我之前跑3Dmark就发现CPU是瓶颈 如果你买一台我们还可以一起做i9版的黑苹果hhh
> > > > > > > > 老了老了，折腾不动了，过去一年被黑苹果搞的好心累。大学的时候熬夜折腾黑苹果感觉超有成就感，现在只求稳定无bug就好，
> > > > > > > > 那我乘大学期间好好折腾吧hhh过几年有钱了买个白苹果
> > > > > > > 
> > > > > > > 
> > > > > > > 我也算是从接触黑苹果开始学习编程，结果现在变成了职业码农。。还是很感谢Hackintosh的 哈哈哈
> > > > > > 
> > > > > > 
> > > > > > 巧了 你编程什么方向啊
> > > > > 
> > > > > 
> > > > > 以前做android app，现在做大数据（hadoop全家桶）和数据挖掘
> > > > 
> > > > 
> > > > 可以 我在搞深度学习 找不到工作就去找你哈哈哈
> > > 
> > > 
> > > 哈哈，我们主要是电商领域，个性化推荐，能上深度就更好啦
> > 
> > 
> > 没事 我毕业还有个两年哈哈哈
> 
> 少年未来可期啊，加油2333

谢谢！
