### ISSUE TITLE
Core i5 install and kernel panic

### ISSUE THREAD

**Issue by cannonfodder728** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#59]
Hello

Sorry if this is a noob question, I'm attempting my first hackintosh.  I've got gen1 x1 extreme with following config

Processor: Intel® Core™ i5-8400H Processor (8M Cache, up to 4.20 GHz)
●  Display Type: 15.6" FHD (1920x1080) anti-glare, LED backlight, IPS w/IR & 720p Camera
●  Memory: 8GB DDR4 2666Mhz SoDIMM Memory
●  Hard Drive: 256GB Solid State Drive M.2
●  Graphics: Intel UHD Graphics 630 in processor and NVIDIA GeForce GTX 1050 Ti
●  Battery: 4 Cell Li-Ion Battery (80Wh)
●  Wireless: Intel Wireless-AC 9560, Wi-Fi 2x2 802.11ac + Bluetooth 5.0, M.2 card

During install I keep getting kernel panic with about 2 minutes left.  I want to hazard that this might be because if dsdt issue but I'm not sure.  Wondering if anyone can help.

Thanks and sorry if this sounds like novice issue.

**Comment by wu-hongjun** [comment]
> Hello
> 
> Sorry if this is a noob question, I'm attempting my first hackintosh. I've got gen1 x1 extreme with following config
> 
> Processor: Intel® Core™ i5-8400H Processor (8M Cache, up to 4.20 GHz)
> ●  Display Type: 15.6" FHD (1920x1080) anti-glare, LED backlight, IPS w/IR & 720p Camera
> ●  Memory: 8GB DDR4 2666Mhz SoDIMM Memory
> ●  Hard Drive: 256GB Solid State Drive M.2
> ●  Graphics: Intel UHD Graphics 630 in processor and NVIDIA GeForce GTX 1050 Ti
> ●  Battery: 4 Cell Li-Ion Battery (80Wh)
> ●  Wireless: Intel Wireless-AC 9560, Wi-Fi 2x2 802.11ac + Bluetooth 5.0, M.2 card
> 
> During install I keep getting kernel panic with about 2 minutes left. I want to hazard that this might be because if dsdt issue but I'm not sure. Wondering if anyone can help.
> 
> Thanks and sorry if this sounds like novice issue.

There are literally one thousand ways to get kernel panics...what I suspect the most is PM981 is not compatible with hackintosh...you’ll need to do more research on tonymacx86...

**Comment by cannonfodder728** [comment]
Sorry for not being specific. The macos installation process sees the nvme and begins installation, but at some stage the machine reboots and I get acpi error ae_not_found.  This makes me think it's an acpi error relayed to dsdt since I've got an core i5 rather than core i7 which the GitHub was designed for.  Just my two cents on what's wrong.

**Comment by wu-hongjun** [comment]
> Sorry for not being specific. The macos installation process sees the nvme and begins installation, but at some stage the machine reboots and I get acpi error ae_not_found. This makes me think it's an acpi error relayed to dsdt since I've got an core i5 rather than core i7 which the GitHub was designed for. Just my two cents on what's wrong.

Honestly hackintoshing is mainly just experimentation. Using other people’s DSDT is troublesome, and since your hardware is very different than mine, you should get rid of my ACPI files, at least my DSDT. You shouldn’t need DSDT for installation anyways it should work.
