### ISSUE TITLE
README for Newbies?

### ISSUE THREAD

**Issue by kunalgrover05** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#6]
Could you add a README or small tutorial for someone to understand how they can set up and get this to running?

**Comment by wu-hongjun** [comment]
You should refer to this install tutorial on TonyMacX86. Swap the EFI folder with mine after you burn your unibeast USB drive, and then install following the tutorial. :)
https://www.tonymacx86.com/threads/unibeast-install-macos-mojave-on-any-supported-intel-based-pc.259381/

**Comment by kunalgrover05** [comment]
Thank you very much.
