### ISSUE TITLE
intel蓝牙驱动的突破

### ISSUE THREAD

**Issue by xiahanting** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#61]
具体请参考
https://github.com/zxystd/IntelBluetoothFirmware
有些人表示9560ac 网卡的蓝牙驱动成功了
我尝试了下，没成功

**Comment by Calciferx** [comment]
蓝牙本来就可以用

**Comment by xiahanting** [comment]
> 蓝牙本来就可以用

本来就可以吗？之前不知道


用上面的驱动，再重新定制usb端口后已经可以驱动9560ac的蓝牙了。

**Comment by xiahanting** [comment]
补充下，该驱动支持冷启动和开关蓝牙

**Comment by Calciferx** [comment]
> 补充下，该驱动支持冷启动和开关蓝牙

等一下，不是说x1 e 的网卡接口是没有usb通道的吗？如果是这样的话通过定制usb驱动蓝牙对x1 e 来说是没有意义的

**Comment by wu-hongjun** [comment]
> > 补充下，该驱动支持冷启动和开关蓝牙
> 
> 等一下，不是说x1 e 的网卡接口是没有usb通道的吗？如果是这样的话通过定制usb驱动蓝牙对x1 e 来说是没有意义的

这一代的蓝牙在CPU里面

**Comment by wu-hongjun** [comment]
> > 补充下，该驱动支持冷启动和开关蓝牙
> 
> 等一下，不是说x1 e 的网卡接口是没有usb通道的吗？如果是这样的话通过定制usb驱动蓝牙对x1 e 来说是没有意义的

Wifi没驱动就没多少意义 还得挂一个wifi usb网卡

**Comment by xiahanting** [comment]
> > > 补充下，该驱动支持冷启动和开关蓝牙
> > 
> > 
> > 等一下，不是说x1 e 的网卡接口是没有usb通道的吗？如果是这样的话通过定制usb驱动蓝牙对x1 e 来说是没有意义的
> 
> Wifi没驱动就没多少意义 还得挂一个wifi usb网卡

主要是目前x1 隐士的BCM94360CS2+转接板方案，性能弱，价格又虚高。之前折腾电脑剩下了usb网卡，先凑合用。
intel 网卡驱动，远景论坛有人在做，等等看。

**Comment by wu-hongjun** [comment]
> > > > 补充下，该驱动支持冷启动和开关蓝牙
> > > 
> > > 
> > > 等一下，不是说x1 e 的网卡接口是没有usb通道的吗？如果是这样的话通过定制usb驱动蓝牙对x1 e 来说是没有意义的
> > 
> > 
> > Wifi没驱动就没多少意义 还得挂一个wifi usb网卡
> 
> 主要是目前x1 隐士的BCM94360CS2+转接板方案，性能弱，价格又虚高。之前折腾电脑剩下了usb网卡，先凑合用。
> intel 网卡驱动，远景论坛有人在做，等等看。

自己焊不就行了 又不难

**Comment by xiahanting** [comment]
> > > > > 补充下，该驱动支持冷启动和开关蓝牙
> > > > 
> > > > 
> > > > 等一下，不是说x1 e 的网卡接口是没有usb通道的吗？如果是这样的话通过定制usb驱动蓝牙对x1 e 来说是没有意义的
> > > 
> > > 
> > > Wifi没驱动就没多少意义 还得挂一个wifi usb网卡
> > 
> > 
> > 主要是目前x1 隐士的BCM94360CS2+转接板方案，性能弱，价格又虚高。之前折腾电脑剩下了usb网卡，先凑合用。
> > intel 网卡驱动，远景论坛有人在做，等等看。
> 
> 自己焊不就行了 又不难

不，对手残党而言，很难，实在没这技术

**Comment by Calciferx** [comment]
> > > > > > 补充下，该驱动支持冷启动和开关蓝牙
> > > > > 
> > > > > 
> > > > > 等一下，不是说x1 e 的网卡接口是没有usb通道的吗？如果是这样的话通过定制usb驱动蓝牙对x1 e 来说是没有意义的
> > > > 
> > > > 
> > > > Wifi没驱动就没多少意义 还得挂一个wifi usb网卡
> > > 
> > > 
> > > 主要是目前x1 隐士的BCM94360CS2+转接板方案，性能弱，价格又虚高。之前折腾电脑剩下了usb网卡，先凑合用。
> > > intel 网卡驱动，远景论坛有人在做，等等看。
> > 
> > 
> > 自己焊不就行了 又不难
> 
> 不，对手残党而言，很难，实在没这技术

哈哈我就是自己焊的，转接卡省出了白果卡的钱
