### ISSUE TITLE
OpenCore/Battery Hot Patching

### ISSUE THREAD

**Issue by averycblack** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#62]
I've managed to get bootcamp switching working with OpenCore, including getting windows to boot through OpenCore. This might be of some interest for anyone that wants to look: https://github.com/1Revenger1/X1-Extreme-OpenCore-Resources

I've also moved all of the battery patches into an SSDT, with method renaming to redirect the calls to the SSDT. This could be useful in Clover as well - as it makes it more likely to not require any new patches when you update the BIOS.

Additionally, NVMeFix is likely to be useful as well. It adds power management and fixes for NVMe drives.

I won't be putting in a pull request for any of this as this repo uses the Multi-beast tools, but if you want the SSDTs or patches for my repo, go ahead.

Edit: I've found that while sleeping this used < 2% battery over the course of two hours as well. I'd guess part of it has to do with NVMe Fixup

**Comment by wu-hongjun** [comment]
I added your support to the Readme.md! Thanks!
