### ISSUE TITLE
求助：因更换主板导致的黑苹果无法启动

### ISSUE THREAD

**Issue by Lumysia** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#65]
- 原因：因为个人原因维修后更换了一块主板
- 做出的工作：
  - 更新BIOS到最新版本（1.27），但是Embedded Controller Version还是旧版本（好像无法更新？）
  - 关闭了安全启动
> 补充：按理来说更换后的主板应该是同型号的吧

- 结果：黑苹果无法启动了，之前制作的启动U盘使用的是您的最新版EFI文件也无法启动
> 补充：因为是4K屏启动的时候花屏也看不清到底哪里错误

> **卑微求助：大佬们可以指点一下吗**

> 附图：AIDA系统概述  
![image.png](https://i.loli.net/2020/03/22/pIESl6iWVorTgOc.png)  
![image.png](https://i.loli.net/2020/03/22/cTeEak2JM4LOG98.png)  
![image.png](https://i.loli.net/2020/03/22/FNv8nb2yH5OqDfm.png)

**Comment by wu-hongjun** [comment]
> * 原因：因为个人原因维修后更换了一块主板
> * 做出的工作：
>   
>   * 更新BIOS到最新版本（1.27），但是Embedded Controller Version还是旧版本（好像无法更新？）
>   * 关闭了安全启动
> 
> > 补充：按理来说更换后的主板应该是同型号的吧
> 
> * 结果：黑苹果无法启动了，之前制作的启动U盘使用的是您的最新版EFI文件也无法启动
> 
> > 补充：因为是4K屏启动的时候花屏也看不清到底哪里错误
> 
> > **卑微求助：大佬们可以指点一下吗**
> 
> > 附图：AIDA系统概述
> > ![image.png](https://camo.githubusercontent.com/0f6566e327fd025b90db62f334b8806e5934bfe9/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30332f32322f704945536c366957566f7254674f632e706e67)
> > ![image.png](https://camo.githubusercontent.com/5af37d24483c429ea1ca9756c0e9a4f22b87426f/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30332f32322f63546545616b324a4d344c4f4739382e706e67)
> > ![image.png](https://camo.githubusercontent.com/9a6cf0b79867ff3419d3fd6373abc1cb0fa07938/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30332f32322f464e76386e62327948354f7144666d2e706e67)

本子卖了🤣不清楚

**Comment by Lumysia** [comment]
好叭

**Comment by wu-hongjun** [comment]
> 好叭

你把USB启动EFI里面花里胡哨的DSDT SSDT KEXT啥的只留下最基本的几个KEXT其他都删了看看能不能至少进一个系统

**Comment by OscarXvita** [comment]
@BloveDawn 可以看看有没有可能是bios里的ME的问题，看看Main菜单底下有没有空值，用meinfo看看你的me状态正不正常，我之前换完主板ME固件都是自己手动重新刷的
