### ISSUE TITLE
经常死机 鼠标不能动的那种

### ISSUE THREAD

**Issue by eunrui** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#67]
重启后也没有崩溃报告 我该如何排查呢
您能给点建议吗？
系统报告如下，红线前是死机的最后一刻
![image](https://user-images.githubusercontent.com/49180440/84758012-77ce1980-aff7-11ea-872d-30254e216d62.png)
这些我在谷歌没有查到原因，而且从进入系统开始就会一直重复循环这些错误报告
![image](https://user-images.githubusercontent.com/49180440/84758246-c7144a00-aff7-11ea-8c48-22340197f747.png)

**Comment by wu-hongjun** [comment]
> 重启后也没有崩溃报告 我该如何排查呢
> 您能给点建议吗？
> 系统报告如下，红线前是死机的最后一刻
> ![image](https://user-images.githubusercontent.com/49180440/84758012-77ce1980-aff7-11ea-872d-30254e216d62.png)
> 这些我在谷歌没有查到原因，而且从进入系统开始就会一直重复循环这些错误报告
> ![image](https://user-images.githubusercontent.com/49180440/84758246-c7144a00-aff7-11ea-8c48-22340197f747.png)

你要不把ACPI东西先删了看看怎么样 这也是玄学 我机子已经卖了

**Comment by eunrui** [comment]
好的 谢谢您的建议 我在尝试自己的DSDT看看效果

**Comment by eunrui** [comment]
em.. 对了 cloverF4提取的ssdt大部分都是有用的吗

**Comment by eunrui** [comment]
以及您的主题升级clover后图标出了一些问题
opencore的话 使用起来如何？

**Comment by wu-hongjun** [comment]
> 以及您的主题升级clover后图标出了一些问题
> opencore的话 使用起来如何？

clover图标我也不知道咋回事 我年初买的最新的Blade用上了opencore老实说没感觉出啥区别

**Comment by eunrui** [comment]
#### Clover图标异常 
> 降级就好了，我记得是5110后才出现的(我降到了5100)

#### com.apple.mdworker.shared 循环写日志问题
> 经查阅貌似是[catalina版本](https://forums.macrumors.com/threads/update-to-10-15-5.2239185/)的问题，
`sudo launchctl unload /System/Library/LaunchAgents/com.apple.mdworker.shared.plist`，
然后将这个plist文件移走或者改个其他格式，反正让系统找不到他就好了，最后重启就不显示了，**暂时不知道后果会有什么，但目前没出什么问题**

#### 死机问题
> 修补了自己提取的dsdt后~~暂时没死机过了~~，顺便解决了睡眠巨耗电的问题（很烦，随机死机的概率仅仅是变少了）
