### ISSUE TITLE
There is not have driver on mojave, but thunderbolt 3 port can work on High Sierra 10.13.6?

### ISSUE THREAD

**Issue by andyy24** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#7]

**Comment by wu-hongjun** [comment]
I tried in 10.13.6 but no response. Please let me know if you made any progress!

**Comment by andyy24** [comment]
OK

**Comment by ghost** [comment]
It sounds like this is unresolved in Mojave, correct? Does it work in High Sierra?

**Comment by wu-hongjun** [comment]
NVIDIA eGPU as a whole is not currently supported by Mojave. We do not know if TB3 works on High Sierra since we decided to move to Mojave. If you can (and have an eGPU) please try it out and tell us what you think!
