### ISSUE TITLE
DSDT无法启动

### ISSUE THREAD

**Issue by wellrex** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#8]
我的机子是ThinkPad P1，用你的DSDT后 v模式出现 ACPI: Executed 44 blocks of module-level executable AML code的错误，按理说2台机子的BIOS是通用的，请问你的BIOS做过什么设置吗？

**Comment by wu-hongjun** [comment]
没有 你也许需要关闭secureboot 这是唯一一点改动

**Comment by wellrex** [comment]
> 没有 你也许需要关闭secureboot 这是唯一一点改动

搞定了，编译了一份自己的dsdt后其他用 zysuper的配置就正常了。
