### ISSUE TITLE
提供一点小小的改进，修正小红点漂移

### ISSUE THREAD

**Issue by andyy24** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#9]
ssdt文件修改来源于 https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller ，可以修正小红点移动过快，漂移的问题。直接开个问题，不pull request了。

[ssdt-clickpad.zip](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/files/2775372/ssdt-clickpad.zip)

**Comment by wu-hongjun** [comment]
收到，你们搞的这个SSDT啊，excited！
https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.14.0.2

I just added these SSDT to ACPI/patched. Thanks.

/**
For those who cannot read Chinese, andyy24 suggested a SSDT to fix the problem of Trackpoint behaving weird or moving too fast using RehabMan's VoodooPS2Controller.kext. I added these files above and drafted a new release(Link above).
*/
